// Nodes
// exported at 2026-06-24 01:37:52 UTC

CREATE (n:`Concept` {`description`: '兰开斯特派徽章；后由都铎玫瑰与约克白玫瑰合并', `name`: '兰开斯特红玫瑰', `name_en`: 'Red Rose of Lancaster'});
CREATE (n:`Concept` {`description`: '金雀花兰开斯特与约克两支系内战；1485年后由都铎巩固和平', `name`: '玫瑰战争', `name_en`: 'Wars of the Roses', `period`: '1455-1487'});
CREATE (n:`Concept` {`description`: '约克派徽章', `name`: '约克白玫瑰', `name_en`: 'White Rose of York'});
CREATE (n:`Concept` {`name`: '英葡同盟'});
CREATE (n:`Dynasty` {`name`: '勃艮第王朝'});
CREATE (n:`Dynasty` {`description`: '987年于格·卡佩起统治法兰西王国的卡佩直系王朝；1328年查理四世无嗣后直系终结，王位由瓦卢瓦旁支继承', `end_year`: 1328, `name`: '卡佩王朝', `name_en`: 'House of Capet', `start_year`: 987});
CREATE (n:`Dynasty` {`description`: '865年埃塞尔雷德一世起至1066年忏悔者爱德华；1016–1042年间英格兰王位由耶灵/克努特系丹麦人占据', `end_year`: 1066, `name`: '威塞克斯王朝', `name_en`: 'House of Wessex', `start_year`: 865});
CREATE (n:`Dynasty` {`description`: '卡佩家族旁支；1328年腓力六世即位后成为统治法兰西的王朝，1589年亨利三世死后由波旁取代', `end_year`: 1589, `name`: '瓦卢瓦王朝', `name_en`: 'House of Valois', `start_year`: 1328});
CREATE (n:`Dynasty` {`description`: '以日德兰耶灵为权力中心的丹麦王室（克努特系）；936年起统一丹麦，986–1014年斯韦恩一世扩张，1016–1035年克努特建立北海帝国；1047年后支系以埃斯特里德森家族延续丹麦王位', `end_year`: 1047, `name`: '耶灵王朝', `name_en`: 'Jelling Dynasty / House of Knýtlinga', `start_year`: 936});
CREATE (n:`Dynasty` {`description`: '威廉征服后统治英格兰的诺曼血统王室，1154 亨利二世即位后转入安茹体系', `name`: '诺曼王朝', `name_en`: 'Norman Dynasty', `period`: '1066-1154'});
CREATE (n:`Dynasty` {`description`: '1154年亨利二世即位至1485年理查三世阵亡；统治英格兰约331年，含安茹、主系、兰开斯特、约克四支；玫瑰战争后由都铎取代', `end_year`: 1485, `name`: '金雀花王朝', `name_en`: 'House of Plantagenet', `start_year`: 1154});
CREATE (n:`Dynasty` {`name`: '阿维斯王朝'});
CREATE (n:`Empire` {`description`: '克努特大帝统治下的北欧海盗帝国，包括英格兰、丹麦、挪威及瑞典南部，是维京时代最后的辉煌', `end_year`: 1035, `government_center`: '伦敦/温切斯特', `name`: '北海帝国', `name_en`: 'North Sea Empire', `period`: '1016-1035', `start_year`: 1016});
CREATE (n:`Event` {`description`: '爱德华长者、埃塞尔斯坦等逐步收复东盎格利亚、五市镇与约克', `name`: '10 世纪收复丹麦法区', `name_en`: 'Anglo-Saxon reconquest of Danelaw', `period_end`: 927, `period_start`: 910});
CREATE (n:`Event` {`description`: '爱德华无嗣去世引发多方争位：哈罗德、威廉与哈德拉达', `name`: '1066 英格兰继承危机', `name_en`: 'English Succession Crisis of 1066', `year`: 1066});
CREATE (n:`Event` {`description`: '腓力四世为对抗教廷征税与动员而召开，王权与等级政治制度化', `name`: '1302年三级会议', `name_en`: 'Estates-General of 1302', `year`: 1302});
CREATE (n:`Event` {`name`: '1373年英葡同盟条约'});
CREATE (n:`Event` {`description`: '瓦特·泰勒等领导的英格兰下层暴动，理查二世时期', `name`: '1381年农民起义', `name_en`: 'Peasants Revolt', `year`: 1381});
CREATE (n:`Event` {`name`: '1383年葡萄牙王位继承危机'});
CREATE (n:`Event` {`name`: '1385年阿勒祖巴洛特战役'});
CREATE (n:`Event` {`name`: '1386年温莎条约'});
CREATE (n:`Event` {`description`: '埃塞尔斯坦宣称统一英格兰王国，丹麦法区作为独立政治区块结束', `name`: '927 年英格兰统一', `name_en`: 'Unification of England 927', `year`: 927});
CREATE (n:`Event` {`description`: '约翰王在兰尼米德被迫签署，限制王权、保障贵族权利', `name`: '《大宪章》', `name_en`: 'Magna Carta', `year`: 1215});
CREATE (n:`Event` {`description`: '爱德华四世重掌局势，沃里克与克拉伦斯逃法', `event_date`: '1470-03-12', `event_type`: 'battle', `name`: '丢盔原野战役', `name_en`: 'Battle of Losecote Field', `victor`: 'york', `year`: 1470});
CREATE (n:`Event` {`description`: '蓝牙哈拉尔受洗并推动丹麦基督教化；耶灵石见证', `name`: '丹麦基督教化', `name_en`: 'Christianization of Denmark', `year`: 965});
CREATE (n:`Event` {`description`: '盎格鲁-撒克逊诸王向维京人支付的赎金/贡赋，与条约和平安排相关', `name`: '丹麦金', `name_en`: 'Danegeld'});
CREATE (n:`Event` {`description`: '卡佩王朝起点；加洛林名义上的王位传承在此转折', `name`: '于格·卡佩加冕', `name_en`: 'Coronation of Hugh Capet', `year`: 987});
CREATE (n:`Event` {`description`: '金雀花王朝对英格兰统治的起点；结束安茹内战与斯蒂芬时期', `name`: '亨利二世即位', `name_en`: 'Accession of Henry II', `year`: 1154});
CREATE (n:`Event` {`description`: '亨利六世死于伦敦塔；兰开斯特名义王位终结', `event_date`: '1471-05-21', `event_type`: 'political', `name`: '亨利六世之死', `name_en`: 'Death of Henry VI in the Tower', `year`: 1471});
CREATE (n:`Event` {`description`: '沃里克与玛格丽特结盟，亨利六世短暂第二次在位', `event_date`: '1470-10', `event_type`: 'political', `name`: '亨利六世复位', `name_en`: 'Readeption of Henry VI', `year`: 1470});
CREATE (n:`Event` {`description`: '爱德华五世与约克公爵理查被囚伦敦塔；理查三世即位后两人下落不明', `event_date`: '1483-06', `event_type`: 'political', `name`: '伦敦塔王子', `name_en`: 'Princes in the Tower', `year`: 1483});
CREATE (n:`Event` {`description`: '约克派俘亨利六世', `event_date`: '1460-07-10', `event_type`: 'battle', `name`: '北安普顿战役（1460）', `name_en`: 'Battle of Northampton (1460)', `victor`: 'york', `year`: 1460});
CREATE (n:`Event` {`description`: '亨利六世保留王位，但理查·约克及其子嗣为法定继承人', `event_date`: '1460-10', `event_type`: 'political', `name`: '协调法案', `name_en`: 'Act of Accord', `year`: 1460});
CREATE (n:`Event` {`description`: '理查三世阵亡，亨利·都铎即位；金雀花王朝终结', `name`: '博斯沃思原野战役', `name_en`: 'Battle of Bosworth Field', `year`: 1485});
CREATE (n:`Event` {`description`: '兰开斯特胜，约克公爵逃爱尔兰；考文垂「魔鬼议会」剥夺约克派', `event_date`: '1459-10-12', `event_type`: 'battle', `name`: '卢德福德桥对峙', `name_en`: 'Battle of Ludford Bridge', `victor`: 'lancaster', `year`: 1459});
CREATE (n:`Event` {`description`: '腓力四世在教会压力下消灭圣殿骑士团并没收财产', `name`: '取缔圣殿骑士团', `name_en`: 'Suppression of the Knights Templar', `year`: 1312});
CREATE (n:`Event` {`description`: '爱德华王子击败并杀死西蒙·德·蒙福尔，亨利三世王权复振', `name`: '埃夫舍姆之战', `name_en`: 'Battle of Evesham', `year`: 1265});
CREATE (n:`Event` {`description`: '沃里克倒戈，爱德华四世一度被囚', `event_date`: '1469-07-26', `event_type`: 'battle', `name`: '埃奇科特穆尔战役', `name_en`: 'Battle of Edgecote Moor', `victor`: 'lancaster', `year`: 1469});
CREATE (n:`Event` {`description`: '865 年入侵英格兰，系统征服并推动维京定居', `name`: '大异教军', `name_en`: 'Great Heathen Army', `year`: 865});
CREATE (n:`Event` {`description`: '北方英军失利，为后续战局铺垫', `name`: '富尔福德门之战', `name_en`: 'Battle of Fulford', `year`: 1066});
CREATE (n:`Event` {`description`: '爱德华四世胜，沃里克伯爵战死', `event_date`: '1471-04-14', `event_type`: 'battle', `name`: '巴尼特战役', `name_en`: 'Battle of Barnet', `victor`: 'york', `year`: 1471});
CREATE (n:`Event` {`description`: '腓力二世击败神圣罗马帝国与英格兰联盟，法兰西王权威信高峰', `name`: '布汶之战', `name_en`: 'Battle of Bouvines', `year`: 1214});
CREATE (n:`Event` {`description`: '1459年约克派小胜', `event_date`: '1459-09-23', `event_type`: 'battle', `name`: '布洛尔希思战役', `name_en`: 'Battle of Blore Heath', `victor`: 'york', `year`: 1459});
CREATE (n:`Event` {`description`: '哈罗德北上击败哈德拉达，但主力疲惫', `name`: '斯坦福桥之战', `name_en`: 'Battle of Stamford Bridge', `year`: 1066});
CREATE (n:`Event` {`description`: '亨利七世镇压兰伯特·西姆内尔叛乱；通常视为玫瑰战争最后一战', `event_date`: '1487-06-16', `event_type`: 'battle', `name`: '斯托克菲尔德战役', `name_en`: 'Battle of Stoke Field', `victor`: 'tudor', `year`: 1487});
CREATE (n:`Event` {`description`: '奥拉夫二世战死，挪威反抗势力被粉碎', `name`: '斯蒂克莱斯塔德战役', `name_en`: 'Battle of Stiklestad', `year`: 1030});
CREATE (n:`Event` {`description`: '1013年斯韦恩再侵英格兰，埃塞尔雷德二世出逃，斯韦恩短暂称王', `name`: '斯韦恩征服英格兰（1013）', `name_en`: 'Sweyn Forkbeard\'s conquest of England 1013', `year`: 1013});
CREATE (n:`Event` {`description`: '斯蒂芬承认亨利（后来的亨利二世）为继承人，结束内战', `name`: '沃灵福德条约', `name_en`: 'Treaty of Wallingford', `year`: 1153});
CREATE (n:`Event` {`description`: '阿尔弗雷德击败古斯伦，为划定丹麦法区边界奠定基础', `name`: '爱丁顿战役', `name_en`: 'Battle of Edington', `year`: 878});
CREATE (n:`Event` {`description`: '卢埃林·阿普·格鲁菲思之死，威尔士并入英格兰王权', `name`: '爱德华一世征服威尔士', `name_en`: 'Conquest of Wales by Edward I', `year`: 1283});
CREATE (n:`Event` {`description`: '1483年4月爱德华四世去世，王位继承之争白热化', `event_date`: '1483-04-09', `event_type`: 'political', `name`: '爱德华四世驾崩', `name_en`: 'Death of Edward IV', `year`: 1483});
CREATE (n:`Event` {`description`: '威尔士亲王爱德华被杀，玛格丽特被俘；兰开斯特男性继承线断绝', `event_date`: '1471-05-04', `event_type`: 'battle', `name`: '特克斯伯里战役', `name_en`: 'Battle of Tewkesbury', `victor`: 'york', `year`: 1471});
CREATE (n:`Event` {`description`: '1455年5月22日第一次圣奥尔本斯；兰开斯特与约克武装冲突正式爆发', `event_date`: '1455-05-22', `name`: '玫瑰战争开端（第一次圣奥尔本斯）', `name_en`: 'Wars of the Roses begins', `year`: 1455});
CREATE (n:`Event` {`description`: '亨利·博林布鲁克返英夺位，金雀花主系终结、兰开斯特支系掌权', `name`: '理查二世被废黜', `name_en`: 'Deposition of Richard II', `year`: 1399});
CREATE (n:`Event` {`description`: '亨利一世与少年菲利普一方对诺曼底威廉的挫败性胜利，但未根除诺曼势力', `name`: '瓦拉维尔之战', `name_en`: 'Battle of Varaville', `year`: 1057});
CREATE (n:`Event` {`description`: '反理查三世；失败，白金汉公爵被处决', `event_date`: '1483-10', `event_type`: 'rebellion', `name`: '白金汉叛乱', `name_en`: 'Buckingham\'s Rebellion', `year`: 1483});
CREATE (n:`Event` {`description`: '爱德华三世宣称法兰西王位，英法长期战争开始', `name`: '百年战争爆发', `name_en`: 'Outbreak of the Hundred Years War', `year`: 1337});
CREATE (n:`Event` {`description`: '玫瑰战争首场大战；约克派胜，萨默塞特公爵被杀', `event_date`: '1455-05-22', `event_type`: 'battle', `name`: '第一次圣奥尔本斯战役', `name_en`: 'First Battle of St Albans', `victor`: 'york', `year`: 1455});
CREATE (n:`Event` {`description`: '路易九世亲征埃及，1249年曼苏拉战败被俘', `name`: '第七次十字军', `name_en`: 'Seventh Crusade', `year`: 1248});
CREATE (n:`Event` {`description`: '兰开斯特胜，夺回亨利六世', `event_date`: '1461-02-17', `event_type`: 'battle', `name`: '第二次圣奥尔本斯战役', `name_en`: 'Second Battle of St Albans', `victor`: 'lancaster', `year`: 1461});
CREATE (n:`Event` {`description`: '约翰王失守，法王将诺曼底等安茹遗产大批并入王室', `name`: '腓力二世收复诺曼底', `name_en`: 'Philip II annexation of Normandy', `year`: 1204});
CREATE (n:`Event` {`description`: '爱德华（约克）击败兰开斯特军队', `event_date`: '1461-02-02', `event_type`: 'battle', `name`: '莫蒂默十字战役', `name_en`: 'Battle of Mortimer\'s Cross', `victor`: 'york', `year`: 1461});
CREATE (n:`Event` {`description`: '威廉登陆英格兰并在黑斯廷斯获胜，最终建立诺曼王权与新秩序', `name`: '诺曼征服', `name_en`: 'Norman Conquest of England', `year`: 1066});
CREATE (n:`Event` {`description`: '菲利普一世年幼，无力干预威廉跨海征服英格兰', `name`: '诺曼征服时期的卡佩摄政', `name_en`: 'Capetian regency during Norman Conquest', `year`: 1066});
CREATE (n:`Event` {`description`: '兰开斯特北方势力遭重创', `event_date`: '1464-05-15', `event_type`: 'battle', `name`: '赫克瑟姆战役', `name_en`: 'Battle of Hexham', `victor`: 'york', `year`: 1464});
CREATE (n:`Event` {`description`: '约克派扫荡北部兰开斯特残部', `event_date`: '1464-04-25', `event_type`: 'battle', `name`: '赫奇利穆尔战役', `name_en`: 'Battle of Hedgeley Moor', `victor`: 'york', `year`: 1464});
CREATE (n:`Event` {`description`: '克努特击败挪威与瑞典联军，确立北欧霸权', `name`: '赫尔格河之战', `name_en`: 'Battle of Helgeå', `year`: 1026});
CREATE (n:`Event` {`description`: '阿基坦归埃莉诺，后嫁亨利二世，安茹—英格兰霸权形成', `name`: '路易七世与埃莉诺离婚', `name_en`: 'Louis VII divorce from Eleanor', `year`: 1152});
CREATE (n:`Event` {`description`: '卡佩从「法兰西岛领主」走向更强王权的阶段标志', `name`: '路易六世整顿王领', `name_en`: 'Louis VI consolidation of royal domain', `year`: 1108});
CREATE (n:`Event` {`description`: '确认边界、丹麦金、古斯伦受洗；丹麦法区范围大致稳定', `name`: '阿尔弗雷德—古斯伦条约', `name_en`: 'Treaty of Alfred and Guthrum', `year`: 886});
CREATE (n:`Event` {`description`: '克努特击败埃德蒙二世，确立对英格兰的统治', `name`: '阿桑顿战役', `name_en`: 'Battle of Assandun', `year`: 1016});
CREATE (n:`Event` {`description`: '亨利五世以少胜多击败法军，百年战争高潮', `name`: '阿金库尔战役', `name_en`: 'Battle of Agincourt', `year`: 1415});
CREATE (n:`Event` {`description`: '玫瑰战争最惨烈一战；约克决定性大胜，爱德华四世走向加冕', `event_date`: '1461-03-29', `event_type`: 'battle', `name`: '陶顿战役', `name_en`: 'Battle of Towton', `victor`: 'york', `year`: 1461});
CREATE (n:`Event` {`description`: '兰开斯特大胜；约克公爵与次子埃德蒙·拉特兰战死', `event_date`: '1460-12-30', `event_type`: 'battle', `name`: '韦克菲尔德战役', `name_en`: 'Battle of Wakefield', `victor`: 'lancaster', `year`: 1460});
CREATE (n:`Event` {`description`: '阿尔弗雷德与古斯伦缔约，划分威塞克斯与维京势力范围', `name`: '韦德莫尔条约', `name_en`: 'Treaty of Wedmore', `year`: 878});
CREATE (n:`Event` {`description`: '威廉击败哈罗德，哈罗德战死，诺曼征服的决定性战役', `name`: '黑斯廷斯之战', `name_en`: 'Battle of Hastings', `year`: 1066});
CREATE (n:`Fief` {`created_year`: 911, `description`: '911年罗洛获封鲁昂一带；942年起统治者多称公爵；1066年后与英格兰王位联动；1204年法王收复大陆诺曼底；1259年英王亨利三世放弃声索；1469年永久并入法兰西王室领地', `fief_type`: '公国', `name`: '诺曼底公国', `name_en`: 'Duchy of Normandy', `post_1204_status`: '1204年起法国王室直接控制大陆诺曼底；英王仅保留海峡群岛相关名义公爵头衔至1259年《巴黎条约》', `title_abolished_note`: '1469年路易十一迫使其弟将诺曼底换为吉耶纳；11月9日诺曼财政厅砸碎公爵戒指，公国不再授予封臣，并入王室领地', `title_abolished_year`: 1469});
CREATE (n:`Institution` {`description`: '教士、贵族、市民代表会议；1302年起成为法王动员与征税的重要工具', `name`: '三级会议', `name_en`: 'Estates-General'});
CREATE (n:`Institution` {`description`: '中世纪西欧宗教权威，常被用于强化征服/统治的正当性叙事', `name`: '教廷', `name_en`: 'Papacy'});
CREATE (n:`Kingdom` {`capital`: '罗斯基勒', `description`: '耶灵王朝本土核心；维京时代后期至克努特北海帝国的权力基座', `name`: '丹麦', `name_en`: 'Denmark', `period_end`: 1035, `period_start`: 1018});
CREATE (n:`Kingdom` {`name`: '卡斯蒂利亚王国'});
CREATE (n:`Kingdom` {`description`: '盎格鲁-撒克逊七国之一；埃塞尔斯坦起多合一为英格兰', `name`: '威塞克斯', `name_en`: 'Wessex'});
CREATE (n:`Kingdom` {`capital`: '特隆赫姆', `description`: '1028–1035年由克努特直接统治；此前与奥拉夫二世长期争夺', `name`: '挪威', `name_en`: 'Norway', `period_end`: 1035, `period_start`: 1028});
CREATE (n:`Kingdom` {`capital`: '巴黎（王室驻跸）', `description`: '中世纪卡佩诸王名义上的封建王国；王权长期限于法兰西岛王领，后逐步扩张', `name`: '法兰西王国', `name_en`: 'Kingdom of France', `period_start`: 987});
CREATE (n:`Kingdom` {`capital`: '锡格蒂纳', `description`: '1026年赫尔河之战后克努特势力所及（斯科讷/梅拉伦湖周边），非全瑞典', `name`: '瑞典南部', `name_en`: 'Southern Sweden', `period_end`: 1035, `period_start`: 1026});
CREATE (n:`Kingdom` {`capital`: '伦敦（王室驻跸）', `description`: '金雀花诸王统治的核心王国；1154-1485年由金雀花及其兰开斯特、约克支系统治', `government_seat`: '威塞克斯', `language`: '古英语、古诺尔斯语', `name`: '英格兰王国', `name_en`: 'Kingdom of England', `period_end`: 1035, `period_start`: 927, `religion`: '基督教'});
CREATE (n:`Kingdom` {`name`: '葡萄牙王国'});
CREATE (n:`Person` {`death_year`: 1018, `description`: '斯韦恩之子、克努特之兄；1014–1018年与克努特争夺丹麦', `identities`: ['丹麦国王'], `is_monarch`: true, `name`: '丹麦哈拉尔二世', `name_en`: 'Harald II of Denmark', `reign_end`: 1018, `reign_start`: 1014});
CREATE (n:`Person` {`death_year`: 1027, `description`: '戈蒂之兄；娶斯韦恩一世之女埃斯特里德（克努特之妹），子斯韦恩二世为丹麦王', `identities`: ['丹麦伯爵'], `name`: '乌尔夫·托吉尔森', `name_en`: 'Ulf Thorgilsson'});
CREATE (n:`Person` {`birth_year`: 1449, `death_year`: 1478, `description`: '1469年曾叛爱德华四世；1478年被处决', `identities`: ['约克派', '爱德华四世之弟'], `name`: '乔治·金雀花（克拉伦斯公爵）', `name_en`: 'George Plantagenet, Duke of Clarence'});
CREATE (n:`Person` {`death_year`: 996, `description`: '987年加冕，终结加洛林直系对王位的占据；开创卡佩世系', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '于格·卡佩', `name_en`: 'Hugh Capet', `reign_end`: 996, `reign_start`: 987});
CREATE (n:`Person` {`death_year`: 1060, `description`: '诺曼底公爵威廉的宗主之一；1057年瓦拉维尔之战试图遏制诺曼底', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '亨利一世', `name_en`: 'Henry I of France', `reign_end`: 1060, `reign_start`: 1031});
CREATE (n:`Person` {`death_year`: 1135, `description`: '颁布《自由宪章》，整顿行政财政，白船号后陷入继承危机', `duke_of_normandy_end`: 1135, `duke_of_normandy_start`: 1106, `identities`: ['英格兰国王', '诺曼底公爵'], `is_monarch`: true, `name`: '亨利一世', `name_en`: 'Henry I of England', `reign_end`: 1135, `reign_start`: 1100});
CREATE (n:`Person` {`description`: '博斯沃思后即位，终结金雀花世系对王位的占据', `identities`: ['英格兰国王', '都铎王朝开国君主'], `is_monarch`: true, `name`: '亨利七世', `name_en`: 'Henry VII of England', `reign_end`: 1509, `reign_start`: 1485});
CREATE (n:`Person` {`death_year`: 1272, `description`: '9岁即位；1258年《牛津条例》与贵族改革；1264-1265年西蒙·德·蒙福尔摄政', `duke_of_normandy_nominal_end`: 1259, `dynasty_branch`: 'main', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '亨利三世', `name_en`: 'Henry III of England', `reign_end`: 1272, `reign_start`: 1216});
CREATE (n:`Person` {`death_year`: 1189, `description`: '玛蒂尔达之子；1154年即位，建立金雀花对英格兰的统治；安茹帝国版图从比利牛斯至苏格兰边境', `duke_of_normandy_end`: 1189, `duke_of_normandy_start`: 1150, `dynasty_branch`: 'angevin', `identities`: ['英格兰国王', '安茹伯爵', '诺曼底公爵', '阿基坦公爵'], `is_monarch`: true, `name`: '亨利二世', `name_en`: 'Henry II of England', `reign_end`: 1189, `reign_start`: 1154});
CREATE (n:`Person` {`death_year`: 1422, `description`: '1415年阿金库尔大胜；《特鲁瓦条约》承认其对法兰西王位继承权', `dynasty_branch`: 'lancaster', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '亨利五世', `name_en`: 'Henry V of England', `reign_end`: 1422, `reign_start`: 1413});
CREATE (n:`Person` {`death_year`: 1471, `description`: '幼主即位；1453年法国失地；玫瑰战争中两次在位，1471年伦敦塔遇害', `dynasty_branch`: 'lancaster', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '亨利六世', `name_en`: 'Henry VI of England', `reign_end`: 1471, `reign_periods`: '1422-1461;1470-1471', `reign_start`: 1422});
CREATE (n:`Person` {`death_year`: 1413, `description`: '冈特的约翰之子；1399年篡位，兰开斯特支系开端', `dynasty_branch`: 'lancaster', `epithet`: '博林布鲁克', `identities`: ['英格兰国王', '兰开斯特支系开国君主'], `is_monarch`: true, `name`: '亨利四世（博林布鲁克）', `name_en`: 'Henry IV of England', `reign_end`: 1413, `reign_start`: 1399});
CREATE (n:`Person` {`birth_year`: 1473, `death_year`: 1483, `description`: '爱德华四世幼子；1483年与兄爱德华五世一同被囚伦敦塔，下落不明', `identities`: ['约克派', '伦敦塔王子'], `name`: '什鲁斯伯里公爵理查（约克王子）', `name_en`: 'Richard of Shrewsbury, Duke of York'});
CREATE (n:`Person` {`death_year`: 1075, `description`: '戈德温之女；1045年嫁忏悔者爱德华，哈罗德由此成为国王内兄（妻兄）', `identities`: ['英格兰王后'], `name`: '伊迪丝（威塞克斯王后）', `name_en`: 'Edith of Wessex', `reign_end`: 1066, `reign_start`: 1045});
CREATE (n:`Person` {`birth_place`: '丹麦', `birth_year`: 995, `death_date`: '1035-11-12', `death_year`: 1035, `description`: '1018年确立丹麦统治；1016年征服英格兰；1028年征服挪威；1026年赫尔河之战后控制瑞典南部；北海帝国建立者', `epithet`: '大帝', `identities`: ['英格兰国王', '丹麦国王', '挪威国王'], `is_monarch`: true, `name`: '克努特大帝', `name_en`: 'Cnut the Great', `reign_end`: 1035, `reign_end_dk`: 1035, `reign_start`: 1016, `reign_start_dk`: 1018});
CREATE (n:`Person` {`birth_year`: 960, `death_year`: 1014, `description`: '986年起统治丹麦；多次入侵英格兰，1013–1014年短暂称英格兰王；1014年卒于根斯索普', `identities`: ['丹麦国王', '挪威国王（宣称）', '英格兰国王（1013-1014）'], `is_monarch`: true, `name`: '八字胡斯韦恩', `name_en`: 'Sweyn Forkbeard', `reign_end`: 1014, `reign_start`: 986});
CREATE (n:`Person` {`description`: '威廉一世时期教会领袖，推动教会诺曼化', `identities`: ['坎特伯雷大 Archbishop'], `name`: '兰弗兰', `name_en`: 'Lanfranc'});
CREATE (n:`Person` {`description`: '与克努特生下哈罗德一世和斯韦恩', `identities`: ['第一任王后'], `name`: '北桑普顿的艾尔夫吉夫', `name_en`: 'Ælfgifu of Northampton'});
CREATE (n:`Person` {`description`: '大异教军领袖之一，与阿尔弗雷德缔约，后受洗改名 Aethelstan', `identities`: ['维京首领'], `name`: '古斯伦', `name_en`: 'Guthrum'});
CREATE (n:`Person` {`death_year`: 1040, `description`: '克努特之子（北安普顿的埃尔弗里嘉所生）；1035-1040年统治英格兰', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '哈拉尔·兔足', `name_en`: 'Harold Harefoot', `reign_end`: 1040, `reign_start`: 1035});
CREATE (n:`Person` {`death_year`: 986, `description`: '统一丹麦并推动基督教化；耶灵石与大型环状要塞（特雷勒堡）为其政绩', `identities`: ['丹麦国王'], `is_monarch`: true, `name`: '哈拉尔·蓝牙', `name_en`: 'Harald Bluetooth', `reign_end`: 986, `reign_start`: 958});
CREATE (n:`Person` {`death_year`: 1042, `description`: '克努特与诺曼的埃玛之子；1035–1042年丹麦国王，1040–1042年兼英格兰国王', `identities`: ['英格兰国王', '丹麦国王'], `is_monarch`: true, `name`: '哈瑟克努特', `name_en`: 'Harthacnut', `reign_end`: 1042, `reign_start`: 1040});
CREATE (n:`Person` {`death_year`: 1066, `description`: '戈德温与戈蒂之子；母系：姨母埃斯特里德为克努特之妹，堂表亲斯韦恩二世为丹麦王；父系联姻：妹伊迪丝为忏悔者爱德华王后，1066年1月获贤人会议拥立', `identities`: ['英格兰国王', '丹麦王室姻亲'], `is_monarch`: true, `name`: '哈罗德·戈德温森', `name_en`: 'Harold Godwinson', `reign_end`: 1066, `reign_start`: 1066});
CREATE (n:`Person` {`death_year`: 939, `description`: '首位广泛称「英格兰人之王」的君主', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '埃塞尔斯坦', `name_en`: 'Aethelstan', `reign_end`: 939, `reign_start`: 924});
CREATE (n:`Person` {`death_year`: 871, `description`: '埃塞尔伍尔夫之子；阿尔弗雷德之兄；抗丹麦战争时期', `identities`: ['威塞克斯国王'], `is_monarch`: true, `name`: '埃塞尔雷德一世', `name_en`: 'Aethelred I of Wessex', `reign_end`: 871, `reign_start`: 865});
CREATE (n:`Person` {`death_year`: 1016, `description`: '埃德加之子；978-1016年在位（1013-1014被克努特短暂取代）', `epithet`: '无准备者', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '埃塞尔雷德二世（无准备者）', `name_en`: 'Aethelred the Unready', `reign_end`: 1016, `reign_periods`: '978-1013;1014-1016', `reign_start`: 978});
CREATE (n:`Person` {`death_year`: 924, `description`: '924年7月即位，约16天后去世；长者爱德华之子', `identities`: ['威塞克斯国王'], `is_monarch`: true, `name`: '埃尔夫威德', `name_en`: 'Aelfweard of Wessex', `reign_end`: 924, `reign_start`: 924});
CREATE (n:`Person` {`death_year`: 975, `description`: '埃德蒙一世之子；埃德威格之弟', `epithet`: '和平者', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '埃德加（和平者）', `name_en`: 'Edgar of England', `reign_end`: 975, `reign_start`: 959});
CREATE (n:`Person` {`death_year`: 959, `description`: '埃德蒙一世之子', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '埃德威格', `name_en`: 'Eadwig of England', `reign_end`: 959, `reign_start`: 955});
CREATE (n:`Person` {`death_year`: 1455, `description`: '1455年第一次圣奥尔本斯战死；兰开斯特对约克的主要对手之一', `identities`: ['兰开斯特派军事领袖'], `name`: '埃德蒙·博福特（萨默塞特公爵）', `name_en`: 'Edmund Beaufort, Duke of Somerset'});
CREATE (n:`Person` {`death_year`: 946, `description`: '埃塞尔斯坦之弟', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '埃德蒙一世', `name_en`: 'Edmund I of England', `reign_end`: 946, `reign_start`: 939});
CREATE (n:`Person` {`death_year`: 1460, `description`: '1460年韦克菲尔德与父亲理查·约克一同被杀', `identities`: ['约克公爵次子'], `name`: '埃德蒙，拉特兰伯爵', `name_en`: 'Edmund, Earl of Rutland'});
CREATE (n:`Person` {`death_year`: 955, `description`: '埃德蒙一世之弟', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '埃德雷德', `name_en`: 'Eadred of England', `reign_end`: 955, `reign_start`: 946});
CREATE (n:`Person` {`description`: '八字胡斯韦恩之女、克努特之妹；嫁乌尔夫，为斯韦恩二世（埃斯特里德森）之母', `identities`: ['丹麦公主', '耶灵王朝成员'], `name`: '埃斯特里德·斯韦恩斯达特', `name_en`: 'Estrid Svendsdatter'});
CREATE (n:`Person` {`name`: '埃莉诺'});
CREATE (n:`Person` {`death_year`: 1030, `description`: '1015–1028年统治挪威；1028年被克努特驱逐，1030年斯蒂克莱斯塔德战死', `identities`: ['挪威国王'], `is_monarch`: true, `name`: '奥拉夫二世（圣奥拉夫）', `name_en`: 'Olaf II of Norway', `reign_end`: 1028, `reign_start`: 1015});
CREATE (n:`Person` {`birth_year`: 1453, `death_year`: 1471, `description`: '亨利六世与玛格丽特之子；1471年特克斯伯里战败被杀', `identities`: ['威尔士亲王', '兰开斯特继承人'], `name`: '威尔士亲王爱德华', `name_en`: 'Edward of Westminster'});
CREATE (n:`Person` {`birth_year`: 1028, `death_year`: 1087, `description`: '黑斯廷斯获胜，建立诺曼土地秩序与城堡体系', `duke_of_normandy_end`: 1087, `duke_of_normandy_start`: 1035, `epithet`: '征服者', `identities`: ['英格兰国王', '诺曼底公爵'], `is_monarch`: true, `name`: '威廉一世', `name_en`: 'William the Conqueror', `regnal_disambiguation`: '英格兰国王世系为威廉一世；诺曼底公爵世系为威廉二世（长剑威廉为诺曼一世）', `regnal_number_england`: 1, `regnal_number_normandy`: 2, `regnal_style_england`: '威廉一世', `regnal_style_normandy`: '威廉二世', `reign_end`: 1087, `reign_start`: 1066});
CREATE (n:`Person` {`death_year`: 942, `description`: '罗洛之子；927年前后继父领导诺曼人；942年在佩罗讷被佛兰德的阿尔努夫一世诱杀', `epithet`: '长剑', `identities`: ['鲁昂伯爵'], `name`: '威廉一世·长剑', `name_en`: 'William Longsword', `regnal_disambiguation`: '诺曼底世系首位威廉（长剑）；非英格兰国王，无英格兰序号', `regnal_number_normandy`: 1, `regnal_style_normandy`: '威廉一世', `reign_end`: 942, `reign_start`: 927});
CREATE (n:`Person` {`death_year`: 1100, `description`: '强化王权与财政，1100 新森林狩猎事故身亡', `epithet`: '红毛威廉', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '威廉二世', `name_en`: 'William Rufus', `regnal_disambiguation`: '英格兰国王世系为威廉二世；诺曼家族世系为威廉三世（未继承诺曼底公爵）', `regnal_number_england`: 2, `regnal_number_normandy`: 3, `regnal_style_england`: '威廉二世', `regnal_style_normandy`: '威廉三世', `reign_end`: 1100, `reign_start`: 1087});
CREATE (n:`Person` {`birth_year`: 1430, `death_year`: 1482, `description`: '亨利六世王后；1450年代起主导兰开斯特军事与政治', `identities`: ['英格兰王后', '兰开斯特派实际领袖'], `name`: '安茹的玛格丽特', `name_en`: 'Margaret of Anjou'});
CREATE (n:`Person` {`death_year`: 1066, `description`: '埃塞尔雷德二世与埃玛之子；1042年威塞克斯血脉复辟；1066年无嗣驾崩', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '忏悔者爱德华', `name_en`: 'Edward the Confessor', `reign_end`: 1066, `reign_start`: 1042});
CREATE (n:`Person` {`description`: '克努特时期重臣，后成为威塞克斯伯爵；与丹麦贵族戈蒂联姻，使戈德温森家族与耶灵王室形成母系姻亲', `identities`: ['威塞克斯伯爵', '赫里福德伯爵'], `name`: '戈德温（威塞克斯伯爵）', `name_en`: 'Godwin of Wessex'});
CREATE (n:`Person` {`birth_year`: 997, `death_year`: 1069, `description`: '丹麦首领托尔吉尔之女；兄乌尔夫娶克努特之妹埃斯特里德，故其子女与丹麦王室为母系姻亲', `identities`: ['丹麦贵族'], `name`: '戈蒂·托克尔之女', `name_en`: 'Gytha Thorkelsdottir'});
CREATE (n:`Person` {`description`: '1485年博斯沃思临阵倒向亨利·都铎，决定战局', `identities`: ['博斯沃思关键倒戈者'], `name`: '托马斯·斯坦利（德比伯爵）', `name_en`: 'Thomas Stanley, Earl of Derby'});
CREATE (n:`Person` {`name`: '斐迪南一世'});
CREATE (n:`Person` {`death_year`: 1154, `description`: '与玛蒂尔达内战，引发无政府状态，1153 沃灵福德条约', `duke_of_normandy_end`: 1144, `duke_of_normandy_start`: 1135, `identities`: ['英格兰国王', '诺曼底公爵'], `is_monarch`: true, `name`: '斯蒂芬', `name_en`: 'Stephen of England', `reign_end`: 1154, `reign_start`: 1135});
CREATE (n:`Person` {`death_year`: 1074, `description`: '克努特之甥（埃斯特里德之子）；1047年自马格努斯手中夺得丹麦，克努特系在丹麦复位', `identities`: ['丹麦国王'], `is_monarch`: true, `name`: '斯韦恩二世（埃斯特里德森）', `name_en`: 'Sweyn II Estridsson', `reign_end`: 1074, `reign_start`: 1047});
CREATE (n:`Person` {`death_year`: 1328, `description`: '卡佩直系末王；1328年无嗣去世，王冠转入瓦卢瓦家族', `epithet`: '美男子', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '查理四世（美男子）', `name_en`: 'Charles IV of France', `reign_end`: 1328, `reign_start`: 1322});
CREATE (n:`Person` {`description`: '内战时期玛蒂尔达阵营核心军事领袖', `identities`: ['玛蒂尔达主要支持者'], `name`: '格洛斯特的罗伯特', `name_en`: 'Robert of Gloucester'});
CREATE (n:`Person` {`death_year`: 978, `description`: '埃德加之子；978年被杀', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '殉教者爱德华', `name_en`: 'Edward the Martyr', `reign_end`: 978, `reign_start`: 975});
CREATE (n:`Person` {`name`: '比阿特丽斯'});
CREATE (n:`Person` {`birth_year`: 1428, `death_year`: 1471, `description`: '先扶爱德华四世，1470年倒向兰开斯特；1471年巴尼特战死', `identities`: ['约克派军事领袖', '造王者'], `name`: '沃里克伯爵（造王者）', `name_en`: 'Richard Neville, Earl of Warwick'});
CREATE (n:`Person` {`death_year`: 1307, `description`: '征服威尔士；对苏格兰用兵，获「苏格兰之锤」之称；1295年召集模范议会', `dynasty_branch`: 'main', `epithet`: '长腿爱德华', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '爱德华一世（长腿爱德华）', `name_en`: 'Edward I of England', `reign_end`: 1307, `reign_start`: 1272});
CREATE (n:`Person` {`death_year`: 1377, `description`: '1337年宣称法兰西王位，开启百年战争；黑死病时期；兰开斯特与约克两支系均出自其子', `dynasty_branch`: 'main', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '爱德华三世', `name_en`: 'Edward III of England', `reign_end`: 1377, `reign_start`: 1327});
CREATE (n:`Person` {`death_year`: 1327, `description`: '1314年班诺克本战败；1327年被王后伊莎贝拉与莫蒂默废黜', `dynasty_branch`: 'main', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '爱德华二世', `name_en`: 'Edward II of England', `reign_end`: 1327, `reign_start`: 1307});
CREATE (n:`Person` {`death_year`: 1483, `description`: '1483年4月即位，6月被叔父理查三世取代；「伦敦塔王子」下落不明', `dynasty_branch`: 'york', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '爱德华五世', `name_en`: 'Edward V of England', `reign_end`: 1483, `reign_start`: 1483});
CREATE (n:`Person` {`death_year`: 1483, `description`: '约克党人；1461年即位，1470-1471年亨利六世短暂复位期间流亡，后复辟', `dynasty_branch`: 'york', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '爱德华四世', `name_en`: 'Edward IV of England', `reign_end`: 1483, `reign_periods`: '1461-1470;1471-1483', `reign_start`: 1461});
CREATE (n:`Person` {`death_year`: 924, `description`: '阿尔弗雷德之子；逐步统一英格兰诸王国', `identities`: ['威塞克斯国王', '盎格鲁-撒克逊人之王'], `is_monarch`: true, `name`: '爱德华长者', `name_en`: 'Edward the Elder', `reign_end`: 924, `reign_start`: 899});
CREATE (n:`Person` {`description`: '斯蒂芬王后，内战时期稳定斯蒂芬阵营', `identities`: ['英格兰王后'], `name`: '玛蒂尔德·德·布洛涅', `name_en`: 'Matilda of Boulogne'});
CREATE (n:`Person` {`description`: '威廉一世王后，巩固诺曼—英格兰联盟', `identities`: ['英格兰王后'], `name`: '玛蒂尔达·德·佛兰德斯', `name_en`: 'Matilda of Flanders'});
CREATE (n:`Person` {`description`: '亨利之女，后与斯蒂芬内战争夺王位', `identities`: ['亨利一世法定继承人'], `name`: '玛蒂尔达皇后', `name_en`: 'Empress Matilda'});
CREATE (n:`Person` {`death_year`: 996, `description`: '长剑之子；Planctus称其为鲁昂伯爵；942–996年巩固诺曼政权并扩张', `epithet`: '无畏者', `identities`: ['诺曼底公爵', '鲁昂伯爵'], `name`: '理查一世（无畏者）', `name_en`: 'Richard I, Duke of Normandy', `reign_end`: 996, `reign_start`: 942});
CREATE (n:`Person` {`death_year`: 1199, `description`: '第三次十字军领袖；长期不在英格兰，王权由摄政治理', `duke_of_normandy_end`: 1199, `duke_of_normandy_start`: 1189, `dynasty_branch`: 'angevin', `epithet`: '狮心王', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '理查一世（狮心王）', `name_en`: 'Richard I of England', `reign_end`: 1199, `reign_start`: 1189});
CREATE (n:`Person` {`death_year`: 1485, `description`: '金雀花末代国王；1485年博斯沃思原野阵亡，都铎的亨利七世继位', `dynasty_branch`: 'york', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '理查三世', `name_en`: 'Richard III of England', `reign_end`: 1485, `reign_start`: 1483});
CREATE (n:`Person` {`death_year`: 1027, `description`: '理查二世长子；在位仅约一年，1027年卒，由弟罗伯特继位', `identities`: ['诺曼底公爵'], `name`: '理查三世', `name_en`: 'Richard III, Duke of Normandy', `reign_end`: 1027, `reign_start`: 1026});
CREATE (n:`Person` {`death_year`: 1400, `description`: '1381年农民起义；1399年被博林布鲁克的亨利废黜，主系终结', `dynasty_branch`: 'main', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '理查二世', `name_en`: 'Richard II of England', `reign_end`: 1399, `reign_start`: 1377});
CREATE (n:`Person` {`death_year`: 1026, `description`: '首位在文献中正式使用「诺曼底公爵」称号的统治者（约1006年起普遍采用）；996–1027年在位', `epithet`: '善良者', `identities`: ['诺曼底公爵'], `name`: '理查二世（善良者）', `name_en`: 'Richard II, Duke of Normandy', `reign_end`: 1027, `reign_start`: 996});
CREATE (n:`Person` {`birth_year`: 1411, `death_year`: 1460, `description`: '爱德华三世后裔；1455-1460年挑战亨利六世；1460年韦克菲尔德战死', `identities`: ['约克派领袖', '英格兰摄政'], `name`: '理查，约克公爵', `name_en`: 'Richard, Duke of York'});
CREATE (n:`Person` {`birth_year`: 1466, `death_year`: 1503, `description`: '爱德华四世长女；1486年与亨利七世联姻，红白玫瑰合一', `identities`: ['约克公主', '英格兰王后'], `name`: '约克的伊丽莎白', `name_en`: 'Elizabeth of York'});
CREATE (n:`Person` {`name`: '约翰·冈特'});
CREATE (n:`Person` {`death_year`: 1216, `description`: '失诺曼底等地；1215年被迫签署《大宪章》；1216年内战期间去世', `duke_of_normandy_end`: 1204, `duke_of_normandy_start`: 1199, `dynasty_branch`: 'angevin', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '约翰王', `name_en`: 'John, King of England', `reign_end`: 1216, `reign_start`: 1199});
CREATE (n:`Person` {`description`: '威廉一世长子，与弟弟们长期争夺诺曼底与英格兰', `duke_of_normandy_end`: 1106, `duke_of_normandy_start`: 1087, `identities`: ['诺曼底公爵'], `name`: '罗伯特·柯索斯', `name_en`: 'Robert Curthose'});
CREATE (n:`Person` {`death_year`: 1035, `description`: '理查二世幼子；1027–1035年公爵；私生子威廉其后继承诺曼底', `epithet`: '宽宏者', `identities`: ['诺曼底公爵'], `name`: '罗伯特一世（宽宏者）', `name_en`: 'Robert I, Duke of Normandy', `reign_end`: 1035, `reign_start`: 1027});
CREATE (n:`Person` {`death_year`: 933, `description`: '约911年法王查理三世授封塞纳河口北岸；当代文献多称诺曼人之首（princeps Nortmannorum），无固定伯爵/公爵头衔；卒于928–933年间', `identities`: ['诺曼人首领', '鲁昂统治者'], `name`: '罗洛', `name_en`: 'Rollo of Normandy', `reign_end`: 927, `reign_start`: 911});
CREATE (n:`Person` {`death_year`: 1031, `description`: '卡佩第二代；与教会关系紧密，王权仍弱', `epithet`: '虔诚者', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '罗贝尔二世（虔诚者）', `name_en`: 'Robert II of France', `reign_end`: 1031, `reign_start`: 996});
CREATE (n:`Person` {`death_year`: 958, `description`: '耶灵王朝第一位有明确史料的丹麦君主；葬于耶灵北冢', `identities`: ['丹麦国王'], `is_monarch`: true, `name`: '老戈姆', `name_en`: 'Gorm the Old', `reign_end`: 958, `reign_start`: 936});
CREATE (n:`Person` {`name`: '胡安一世'});
CREATE (n:`Person` {`death_year`: 1285, `description`: '延续向南扩张；1285年征阿拉贡时阵亡', `epithet`: '硬汉子', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '腓力三世（硬汉子）', `name_en`: 'Philip III of France', `reign_end`: 1285, `reign_start`: 1270});
CREATE (n:`Person` {`death_year`: 1223, `description`: '击败安茹帝国；1204年收复诺曼底等地；1214年布汶之战确立法国优势', `epithet`: '奥古斯都', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '腓力二世（奥古斯都）', `name_en`: 'Philip II of France', `reign_end`: 1223, `reign_start`: 1180});
CREATE (n:`Person` {`death_year`: 1322, `description`: '1316年即位；涉及萨利克法与女性/母系继承争议', `epithet`: '长人', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '腓力五世（长人）', `name_en`: 'Philip V of France', `reign_end`: 1322, `reign_start`: 1316});
CREATE (n:`Person` {`death_year`: 1350, `description`: '瓦卢瓦的查理之孙、腓力四世侄孙；1328年加冕，卡佩直系终结后首位法王，百年战争前夕', `epithet`: '瓦卢瓦的', `identities`: ['法兰西国王（瓦卢瓦支系）', '瓦卢瓦王朝开国君主'], `is_monarch`: true, `name`: '腓力六世', `name_en`: 'Philip VI of France', `reign_end`: 1350, `reign_start`: 1328});
CREATE (n:`Person` {`death_year`: 1314, `description`: '强化王权对抗教廷；1302年召开三级会议；1312年取缔圣殿骑士团', `epithet`: '美男子', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '腓力四世（美男子）', `name_en`: 'Philip IV of France', `reign_end`: 1314, `reign_start`: 1285});
CREATE (n:`Person` {`name`: '航海家亨利'});
CREATE (n:`Person` {`death_year`: 1151, `description`: '安茹伯；1144年1月进入鲁昂，夏宣称诺曼底公爵；1149–1150年与玛蒂尔达将公国让予其子亨利，1150年法王路易七世正式承认', `epithet`: '美男子 / Plantagenet', `identities`: ['安茹伯爵', '诺曼底公爵'], `name`: '若弗鲁瓦五世（美男子）', `name_en`: 'Geoffrey V, Count of Anjou', `reign_end`: 1150, `reign_start`: 1144});
CREATE (n:`Person` {`name`: '若昂一世'});
CREATE (n:`Person` {`name`: '菲利帕'});
CREATE (n:`Person` {`death_year`: 1108, `description`: '1060年幼龄即位；1066年诺曼征服时仍由摄政，王权孱弱', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '菲利普一世', `name_en`: 'Philip I of France', `reign_end`: 1108, `reign_start`: 1060});
CREATE (n:`Person` {`birth_year`: 985, `death_year`: 1052, `description`: '前英格兰王埃塞尔雷德二世的遗孀，克努特的第二任王后', `identities`: ['王后'], `name`: '诺曼底的埃玛', `name_en`: 'Emma of Normandy'});
CREATE (n:`Person` {`death_year`: 1180, `description`: '参加第二次十字军；1152年与阿基坦的埃莉诺离婚，安茹—英格兰势力坐大', `epithet`: '幼王', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '路易七世（幼王）', `name_en`: 'Louis VII of France', `reign_end`: 1180, `reign_start`: 1137});
CREATE (n:`Person` {`death_year`: 1270, `description`: '中世纪法兰西模范君主；第七次十字军；1297年封圣', `epithet`: '圣路易', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '路易九世（圣路易）', `name_en`: 'Louis IX of France', `reign_end`: 1270, `reign_start`: 1226});
CREATE (n:`Person` {`death_year`: 1226, `description`: '短暂在位；阿尔比十字军后期作为王太子已参与南方战事', `epithet`: '狮子', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '路易八世（狮子）', `name_en`: 'Louis VIII of France', `reign_end`: 1226, `reign_start`: 1223});
CREATE (n:`Person` {`death_year`: 1137, `description`: '整顿王领、打击地方豪强，卡佩王权实质性巩固的起点', `epithet`: '胖子', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '路易六世（胖子）', `name_en`: 'Louis VI of France', `reign_end`: 1137, `reign_start`: 1108});
CREATE (n:`Person` {`death_year`: 1316, `description`: '卡佩末代直系之一；在位短暂', `epithet`: '争吵者', `identities`: ['法兰西国王'], `is_monarch`: true, `name`: '路易十世（争吵者）', `name_en`: 'Louis X of France', `reign_end`: 1316, `reign_start`: 1314});
CREATE (n:`Person` {`death_year`: 1016, `description`: '埃塞尔雷德二世之子；1016年与克努特瓜分英格兰后同年去世', `epithet`: '铁甲', `identities`: ['英格兰国王'], `is_monarch`: true, `name`: '铁甲埃德蒙', `name_en`: 'Edmund Ironside', `reign_end`: 1016, `reign_start`: 1016});
CREATE (n:`Person` {`death_year`: 899, `description`: '唯一称「大帝」的英格兰君主；约886年起称盎格鲁-撒克逊人之王', `identities`: ['威塞克斯国王', '盎格鲁-撒克逊人之王'], `is_monarch`: true, `name`: '阿尔弗雷德大帝', `name_en`: 'Alfred the Great', `reign_end`: 899, `reign_start`: 871});
CREATE (n:`Person` {`name`: '阿方索一世'});
CREATE (n:`Person` {`death_year`: 1047, `description`: '奥拉夫二世之子；1035年起据挪威，1042年哈瑟克努特死后兼丹麦王位至1047年', `identities`: ['挪威国王', '丹麦国王'], `is_monarch`: true, `name`: '马格努斯一世（好人）', `name_en`: 'Magnus the Good', `reign_end`: 1047, `reign_start`: 1035});
