// Relationships
// exported at 2026-06-24 01:37:52 UTC

MATCH (a:`Person` {`name`: '丹麦哈拉尔二世'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '于格·卡佩'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '亨利一世'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '亨利一世'}) MATCH (b:`Dynasty` {`name`: '诺曼王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·兔足'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·蓝牙'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '哈瑟克努特'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔斯坦'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德一世'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃尔夫威德'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃德加（和平者）'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃德威格'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃德蒙一世'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃德雷德'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '埃斯特里德·斯韦恩斯达特'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Dynasty` {`name`: '诺曼王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '威廉二世'}) MATCH (b:`Dynasty` {`name`: '诺曼王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '忏悔者爱德华'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '斐迪南一世'}) MATCH (b:`Dynasty` {`name`: '勃艮第王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '斯蒂芬'}) MATCH (b:`Dynasty` {`name`: '诺曼王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '斯韦恩二世（埃斯特里德森）'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '查理四世（美男子）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '殉教者爱德华'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '爱德华长者'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '罗洛'}) MATCH (b:`Dynasty` {`name`: '诺曼王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '罗贝尔二世（虔诚者）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '老戈姆'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '腓力三世（硬汉子）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '腓力二世（奥古斯都）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '腓力五世（长人）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '腓力六世'}) MATCH (b:`Dynasty` {`name`: '瓦卢瓦王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '腓力四世（美男子）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '若昂一世'}) MATCH (b:`Dynasty` {`name`: '阿维斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '菲利普一世'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '路易七世（幼王）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '路易九世（圣路易）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '路易八世（狮子）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '路易六世（胖子）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '路易十世（争吵者）'}) MATCH (b:`Dynasty` {`name`: '卡佩王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '铁甲埃德蒙'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '阿尔弗雷德大帝'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Person` {`name`: '阿方索一世'}) MATCH (b:`Dynasty` {`name`: '勃艮第王朝'}) CREATE (a)-[:`BELONGED_TO`]->(b);
MATCH (a:`Event` {`name`: '韦德莫尔条约'}) MATCH (b:`Kingdom` {`name`: '威塞克斯'}) CREATE (a)-[:`BORDERED`]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`CLAIMED_THRONE_OF`]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Event` {`name`: '黑斯廷斯之战'}) CREATE (a)-[:`CLAIMED_THRONE_OF`]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`CLAIMED_THRONE_OF`]->(b);
MATCH (a:`Person` {`name`: '胡安一世'}) MATCH (b:`Kingdom` {`name`: '葡萄牙王国'}) CREATE (a)-[:`CLAIMED_THRONE_OF`]->(b);
MATCH (a:`Event` {`name`: '1066 英格兰继承危机'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`CONCERNS`]->(b);
MATCH (a:`Event` {`name`: '1383年葡萄牙王位继承危机'}) MATCH (b:`Person` {`name`: '比阿特丽斯'}) CREATE (a)-[:`CONCERNS`]->(b);
MATCH (a:`Event` {`name`: '1383年葡萄牙王位继承危机'}) MATCH (b:`Person` {`name`: '胡安一世'}) CREATE (a)-[:`CONCERNS`]->(b);
MATCH (a:`Event` {`name`: '1383年葡萄牙王位继承危机'}) MATCH (b:`Person` {`name`: '若昂一世'}) CREATE (a)-[:`CONCERNS`]->(b);
MATCH (a:`Event` {`name`: '诺曼征服'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`CONCERNS`]->(b);
MATCH (a:`Person` {`name`: '古斯伦'}) MATCH (b:`Event` {`name`: '爱丁顿战役'}) CREATE (a)-[:`DEFEATED_AT`]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Event` {`name`: '黑斯廷斯之战'}) CREATE (a)-[:`DIED_AT`]->(b);
MATCH (a:`Empire` {`name`: '北海帝国'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`DISSOLVED_AFTER` {`description`: '1035年克努特卒，北海帝国分裂', `year`: 1035}]->(b);
MATCH (a:`Event` {`name`: '博斯沃思原野战役'}) MATCH (b:`Dynasty` {`name`: '金雀花王朝'}) CREATE (a)-[:`ENDED`]->(b);
MATCH (a:`Event` {`name`: '腓力二世收复诺曼底'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`ENDED_ANGEVIN_RULE_IN`]->(b);
MATCH (a:`Event` {`name`: '1386年温莎条约'}) MATCH (b:`Concept` {`name`: '英葡同盟'}) CREATE (a)-[:`ESTABLISHED`]->(b);
MATCH (a:`Event` {`name`: '亨利二世即位'}) MATCH (b:`Dynasty` {`name`: '金雀花王朝'}) CREATE (a)-[:`ESTABLISHED`]->(b);
MATCH (a:`Event` {`name`: '诺曼征服'}) MATCH (b:`Person` {`name`: '威廉一世'}) CREATE (a)-[:`ESTABLISHED_REIGN_OF`]->(b);
MATCH (a:`Person` {`name`: '乌尔夫·托吉尔森'}) MATCH (b:`Person` {`name`: '斯韦恩二世（埃斯特里德森）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '亨利三世'}) MATCH (b:`Person` {`name`: '爱德华一世（长腿爱德华）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '亨利二世'}) MATCH (b:`Person` {`name`: '理查一世（狮心王）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '亨利二世'}) MATCH (b:`Person` {`name`: '约翰王'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '亨利五世'}) MATCH (b:`Person` {`name`: '亨利六世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Person` {`name`: '威尔士亲王爱德华'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '亨利四世（博林布鲁克）'}) MATCH (b:`Person` {`name`: '亨利五世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '哈拉尔·兔足'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '哈瑟克努特'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Person` {`name`: '丹麦哈拉尔二世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Person` {`name`: '埃斯特里德·斯韦恩斯达特'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·蓝牙'}) MATCH (b:`Person` {`name`: '八字胡斯韦恩'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) MATCH (b:`Person` {`name`: '忏悔者爱德华'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) MATCH (b:`Person` {`name`: '铁甲埃德蒙'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '埃德加（和平者）'}) MATCH (b:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '埃德加（和平者）'}) MATCH (b:`Person` {`name`: '殉教者爱德华'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '埃德蒙一世'}) MATCH (b:`Person` {`name`: '埃德加（和平者）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '埃德蒙一世'}) MATCH (b:`Person` {`name`: '埃德威格'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '埃德蒙一世'}) MATCH (b:`Person` {`name`: '埃德雷德'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '奥拉夫二世（圣奥拉夫）'}) MATCH (b:`Person` {`name`: '马格努斯一世（好人）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Person` {`name`: '亨利一世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Person` {`name`: '威廉二世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Person` {`name`: '罗伯特·柯索斯'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '威廉一世·长剑'}) MATCH (b:`Person` {`name`: '理查一世（无畏者）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '戈德温（威塞克斯伯爵）'}) MATCH (b:`Person` {`name`: '伊迪丝（威塞克斯王后）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '戈德温（威塞克斯伯爵）'}) MATCH (b:`Person` {`name`: '哈罗德·戈德温森'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '斐迪南一世'}) MATCH (b:`Person` {`name`: '比阿特丽斯'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华一世（长腿爱德华）'}) MATCH (b:`Person` {`name`: '爱德华二世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华三世'}) MATCH (b:`Person` {`name`: '约翰·冈特'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华二世'}) MATCH (b:`Person` {`name`: '爱德华三世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Person` {`name`: '什鲁斯伯里公爵理查（约克王子）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Person` {`name`: '爱德华五世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Person` {`name`: '理查三世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Person` {`name`: '约克的伊丽莎白'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华长者'}) MATCH (b:`Person` {`name`: '埃塞尔斯坦'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华长者'}) MATCH (b:`Person` {`name`: '埃尔夫威德'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '爱德华长者'}) MATCH (b:`Person` {`name`: '埃德蒙一世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '理查一世（无畏者）'}) MATCH (b:`Person` {`name`: '理查二世（善良者）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '理查二世（善良者）'}) MATCH (b:`Person` {`name`: '理查三世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '理查二世（善良者）'}) MATCH (b:`Person` {`name`: '罗伯特一世（宽宏者）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Person` {`name`: '乔治·金雀花（克拉伦斯公爵）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Person` {`name`: '埃德蒙，拉特兰伯爵'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Person` {`name`: '爱德华四世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Person` {`name`: '理查三世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '约翰·冈特'}) MATCH (b:`Person` {`name`: '亨利四世（博林布鲁克）'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '约翰·冈特'}) MATCH (b:`Person` {`name`: '菲利帕'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '约翰王'}) MATCH (b:`Person` {`name`: '亨利三世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '罗伯特一世（宽宏者）'}) MATCH (b:`Person` {`name`: '威廉一世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '罗洛'}) MATCH (b:`Person` {`name`: '威廉一世·长剑'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '老戈姆'}) MATCH (b:`Person` {`name`: '哈拉尔·蓝牙'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '若弗鲁瓦五世（美男子）'}) MATCH (b:`Person` {`name`: '亨利二世'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '若昂一世'}) MATCH (b:`Person` {`name`: '航海家亨利'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Person` {`name`: '阿尔弗雷德大帝'}) MATCH (b:`Person` {`name`: '爱德华长者'}) CREATE (a)-[:`FATHER_OF`]->(b);
MATCH (a:`Empire` {`name`: '北海帝国'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`FOUNDED_BY`]->(b);
MATCH (a:`Dynasty` {`name`: '勃艮第王朝'}) MATCH (b:`Person` {`name`: '阿方索一世'}) CREATE (a)-[:`HAS_FOUNDER`]->(b);
MATCH (a:`Dynasty` {`name`: '卡佩王朝'}) MATCH (b:`Person` {`name`: '于格·卡佩'}) CREATE (a)-[:`HAS_FOUNDER` {`branch`: 'angevin', `description`: '987年加冕，开创卡佩王朝', `name`: '开创者', `year`: 987}]->(b);
MATCH (a:`Dynasty` {`name`: '威塞克斯王朝'}) MATCH (b:`Person` {`name`: '埃塞尔雷德一世'}) CREATE (a)-[:`HAS_FOUNDER` {`description`: '865年起本支系连续统治威塞克斯/英格兰（至1016；1042年复辟）', `year`: 865}]->(b);
MATCH (a:`Dynasty` {`name`: '瓦卢瓦王朝'}) MATCH (b:`Person` {`name`: '腓力六世'}) CREATE (a)-[:`HAS_FOUNDER` {`branch`: 'angevin', `description`: '1328年加冕，瓦卢瓦王朝首位法兰西国王', `name`: '开创者', `year`: 1328}]->(b);
MATCH (a:`Dynasty` {`name`: '耶灵王朝'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`HAS_FOUNDER` {`description`: '1016-1042年统治英格兰的克努特系（耶灵王朝支系）', `scope`: '英格兰', `year`: 1016}]->(b);
MATCH (a:`Dynasty` {`name`: '耶灵王朝'}) MATCH (b:`Person` {`name`: '老戈姆'}) CREATE (a)-[:`HAS_FOUNDER` {`description`: '老戈姆为耶灵王朝在丹麦的奠基者', `scope`: '丹麦/斯堪的纳维亚', `year`: 936}]->(b);
MATCH (a:`Dynasty` {`name`: '金雀花王朝'}) MATCH (b:`Person` {`name`: '亨利二世'}) CREATE (a)-[:`HAS_FOUNDER` {`branch`: 'angevin', `description`: '1154年即位，开创金雀花对英格兰的统治', `name`: '开创者', `year`: 1154}]->(b);
MATCH (a:`Dynasty` {`name`: '阿维斯王朝'}) MATCH (b:`Person` {`name`: '若昂一世'}) CREATE (a)-[:`HAS_FOUNDER`]->(b);
MATCH (a:`Empire` {`name`: '北海帝国'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`INCLUDED` {`period`: '1018-1035', `status`: '核心王国'}]->(b);
MATCH (a:`Empire` {`name`: '北海帝国'}) MATCH (b:`Kingdom` {`name`: '挪威'}) CREATE (a)-[:`INCLUDED` {`period`: '1028-1035', `status`: '征服王国'}]->(b);
MATCH (a:`Empire` {`name`: '北海帝国'}) MATCH (b:`Kingdom` {`name`: '瑞典南部'}) CREATE (a)-[:`INCLUDED` {`period`: '1026-1035', `status`: '势力范围'}]->(b);
MATCH (a:`Empire` {`name`: '北海帝国'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`INCLUDED` {`period`: '1016-1035', `status`: '核心王国'}]->(b);
MATCH (a:`Event` {`name`: '丢盔原野战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '亨利六世之死'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '亨利六世复位'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '伦敦塔王子'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '北安普顿战役（1460）'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '协调法案'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '博斯沃思原野战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '卢德福德桥对峙'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '埃奇科特穆尔战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '巴尼特战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '布洛尔希思战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '斯托克菲尔德战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '爱德华四世驾崩'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '特克斯伯里战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '玫瑰战争开端（第一次圣奥尔本斯）'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '白金汉叛乱'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '第一次圣奥尔本斯战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '第二次圣奥尔本斯战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '莫蒂默十字战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '赫克瑟姆战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '赫奇利穆尔战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '陶顿战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Event` {`name`: '韦克菲尔德战役'}) MATCH (b:`Concept` {`name`: '玫瑰战争'}) CREATE (a)-[:`INSTANCE_OF`]->(b);
MATCH (a:`Concept` {`name`: '英葡同盟'}) MATCH (b:`Event` {`name`: '1385年阿勒祖巴洛特战役'}) CREATE (a)-[:`INVOKED_IN`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔斯坦'}) MATCH (b:`Event` {`name`: '10 世纪收复丹麦法区'}) CREATE (a)-[:`LED`]->(b);
MATCH (a:`Person` {`name`: '爱德华长者'}) MATCH (b:`Event` {`name`: '10 世纪收复丹麦法区'}) CREATE (a)-[:`LED`]->(b);
MATCH (a:`Event` {`name`: '1066 英格兰继承危机'}) MATCH (b:`Event` {`name`: '黑斯廷斯之战'}) CREATE (a)-[:`LED_TO`]->(b);
MATCH (a:`Event` {`name`: '1383年葡萄牙王位继承危机'}) MATCH (b:`Event` {`name`: '1385年阿勒祖巴洛特战役'}) CREATE (a)-[:`LED_TO`]->(b);
MATCH (a:`Person` {`name`: '约翰王'}) MATCH (b:`Person` {`name`: '腓力二世（奥古斯都）'}) CREATE (a)-[:`LOST_DUCHY_TO` {`description`: '1204年腓力二世奥古斯都征服诺曼底大陆；安茹帝国丧失该公国实权', `inherited_title`: '诺曼底公爵', `succession_type`: '法王征服', `title`: '诺曼底公爵', `year`: 1204}]->(b);
MATCH (a:`Person` {`name`: '乌尔夫·托吉尔森'}) MATCH (b:`Person` {`name`: '埃斯特里德·斯韦恩斯达特'}) CREATE (a)-[:`MARRIED_TO` {`description`: '乌尔夫娶克努特之妹埃斯特里德，其子斯韦恩二世为丹麦国王（埃斯特里德森王朝）', `year`: 1022}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '北桑普顿的艾尔夫吉夫'}) CREATE (a)-[:`MARRIED_TO` {`order`: '第一任'}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '诺曼底的埃玛'}) CREATE (a)-[:`MARRIED_TO` {`order`: '第二任', `year`: 1017}]->(b);
MATCH (a:`Person` {`name`: '忏悔者爱德华'}) MATCH (b:`Person` {`name`: '伊迪丝（威塞克斯王后）'}) CREATE (a)-[:`MARRIED_TO` {`day`: 23, `description`: '1045年1月23日加冕王后；哈罗德·戈德温森为其兄', `month`: 1, `year`: 1045}]->(b);
MATCH (a:`Person` {`name`: '戈德温（威塞克斯伯爵）'}) MATCH (b:`Person` {`name`: '戈蒂·托克尔之女'}) CREATE (a)-[:`MARRIED_TO` {`description`: '约1022–1023年联姻；戈蒂为乌尔夫之妹，乌尔夫娶克努特之妹，巩固盎格鲁—斯堪的纳维亚贵族联盟', `order`: '联姻', `year`: 1022}]->(b);
MATCH (a:`Person` {`name`: '斯蒂芬'}) MATCH (b:`Person` {`name`: '玛蒂尔德·德·布洛涅'}) CREATE (a)-[:`MARRIED_TO`]->(b);
MATCH (a:`Person` {`name`: '比阿特丽斯'}) MATCH (b:`Person` {`name`: '胡安一世'}) CREATE (a)-[:`MARRIED_TO`]->(b);
MATCH (a:`Person` {`name`: '胡安一世'}) MATCH (b:`Person` {`name`: '比阿特丽斯'}) CREATE (a)-[:`MARRIED_TO`]->(b);
MATCH (a:`Person` {`name`: '若昂一世'}) MATCH (b:`Person` {`name`: '菲利帕'}) CREATE (a)-[:`MARRIED_TO`]->(b);
MATCH (a:`Person` {`name`: '戈蒂·托克尔之女'}) MATCH (b:`Person` {`name`: '伊迪丝（威塞克斯王后）'}) CREATE (a)-[:`MOTHER_OF`]->(b);
MATCH (a:`Person` {`name`: '戈蒂·托克尔之女'}) MATCH (b:`Person` {`name`: '哈罗德·戈德温森'}) CREATE (a)-[:`MOTHER_OF`]->(b);
MATCH (a:`Person` {`name`: '玛蒂尔达皇后'}) MATCH (b:`Person` {`name`: '亨利二世'}) CREATE (a)-[:`MOTHER_OF`]->(b);
MATCH (a:`Person` {`name`: '菲利帕'}) MATCH (b:`Person` {`name`: '航海家亨利'}) CREATE (a)-[:`MOTHER_OF`]->(b);
MATCH (a:`Person` {`name`: '古斯伦'}) MATCH (b:`Event` {`name`: '阿尔弗雷德—古斯伦条约'}) CREATE (a)-[:`NEGOTIATED`]->(b);
MATCH (a:`Person` {`name`: '古斯伦'}) MATCH (b:`Event` {`name`: '韦德莫尔条约'}) CREATE (a)-[:`NEGOTIATED`]->(b);
MATCH (a:`Person` {`name`: '阿尔弗雷德大帝'}) MATCH (b:`Event` {`name`: '阿尔弗雷德—古斯伦条约'}) CREATE (a)-[:`NEGOTIATED`]->(b);
MATCH (a:`Person` {`name`: '阿尔弗雷德大帝'}) MATCH (b:`Event` {`name`: '韦德莫尔条约'}) CREATE (a)-[:`NEGOTIATED`]->(b);
MATCH (a:`Person` {`name`: '亨利七世'}) MATCH (b:`Event` {`name`: '博斯沃思原野战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster/tudor', `role`: '胜利者'}]->(b);
MATCH (a:`Person` {`name`: '亨利七世'}) MATCH (b:`Event` {`name`: '斯托克菲尔德战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'tudor', `role`: '胜利者'}]->(b);
MATCH (a:`Person` {`name`: '亨利三世'}) MATCH (b:`Event` {`name`: '埃夫舍姆之战'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '一方君主'}]->(b);
MATCH (a:`Person` {`name`: '亨利二世'}) MATCH (b:`Event` {`name`: '亨利二世即位'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '主角'}]->(b);
MATCH (a:`Person` {`name`: '亨利五世'}) MATCH (b:`Event` {`name`: '阿金库尔战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '统帅'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Event` {`name`: '亨利六世之死'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '死者'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Event` {`name`: '亨利六世复位'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '复位君主'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Event` {`name`: '北安普顿战役（1460）'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '被俘'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Event` {`name`: '协调法案'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '在位君主'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Event` {`name`: '玫瑰战争开端（第一次圣奥尔本斯）'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '兰开斯特一方'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Event` {`name`: '第一次圣奥尔本斯战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '被俘一方君主'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Event` {`name`: '第二次圣奥尔本斯战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '被夺回'}]->(b);
MATCH (a:`Person` {`name`: '亨利四世（博林布鲁克）'}) MATCH (b:`Event` {`name`: '理查二世被废黜'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '夺位者'}]->(b);
MATCH (a:`Person` {`name`: '什鲁斯伯里公爵理查（约克王子）'}) MATCH (b:`Event` {`name`: '伦敦塔王子'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '失踪王子'}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Event` {`name`: '斯蒂克莱斯塔德战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '幕后指挥', `year`: 1030}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Event` {`name`: '赫尔格河之战'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '胜利者', `year`: 1026}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Event` {`name`: '阿桑顿战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '胜利者', `year`: 1016}]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Event` {`name`: '斯韦恩征服英格兰（1013）'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '征服者'}]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·蓝牙'}) MATCH (b:`Event` {`name`: '丹麦基督教化'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '推动者'}]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Event` {`name`: '1066 英格兰继承危机'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '被推选的国王'}]->(b);
MATCH (a:`Person` {`name`: '埃德蒙·博福特（萨默塞特公爵）'}) MATCH (b:`Event` {`name`: '第一次圣奥尔本斯战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '阵亡'}]->(b);
MATCH (a:`Person` {`name`: '埃德蒙，拉特兰伯爵'}) MATCH (b:`Event` {`name`: '韦克菲尔德战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '阵亡'}]->(b);
MATCH (a:`Person` {`name`: '埃莉诺'}) MATCH (b:`Event` {`name`: '1373年英葡同盟条约'}) CREATE (a)-[:`PARTICIPATED_IN`]->(b);
MATCH (a:`Person` {`name`: '奥拉夫二世（圣奥拉夫）'}) MATCH (b:`Event` {`name`: '斯蒂克莱斯塔德战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '阵亡者'}]->(b);
MATCH (a:`Person` {`name`: '威尔士亲王爱德华'}) MATCH (b:`Event` {`name`: '特克斯伯里战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '阵亡'}]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Event` {`name`: '诺曼征服'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '征服者'}]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Event` {`name`: '黑斯廷斯之战'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '胜利者'}]->(b);
MATCH (a:`Person` {`name`: '安茹的玛格丽特'}) MATCH (b:`Event` {`name`: '特克斯伯里战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '被俘'}]->(b);
MATCH (a:`Person` {`name`: '安茹的玛格丽特'}) MATCH (b:`Event` {`name`: '第二次圣奥尔本斯战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '兰开斯特一方'}]->(b);
MATCH (a:`Person` {`name`: '安茹的玛格丽特'}) MATCH (b:`Event` {`name`: '陶顿战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '败退'}]->(b);
MATCH (a:`Person` {`name`: '安茹的玛格丽特'}) MATCH (b:`Event` {`name`: '韦克菲尔德战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '兰开斯特一方'}]->(b);
MATCH (a:`Person` {`name`: '忏悔者爱德华'}) MATCH (b:`Event` {`name`: '1066 英格兰继承危机'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '无嗣驾崩'}]->(b);
MATCH (a:`Person` {`name`: '托马斯·斯坦利（德比伯爵）'}) MATCH (b:`Event` {`name`: '博斯沃思原野战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'neutral', `role`: '决定性倒戈'}]->(b);
MATCH (a:`Person` {`name`: '斐迪南一世'}) MATCH (b:`Event` {`name`: '1373年英葡同盟条约'}) CREATE (a)-[:`PARTICIPATED_IN`]->(b);
MATCH (a:`Person` {`name`: '沃里克伯爵（造王者）'}) MATCH (b:`Event` {`name`: '亨利六世复位'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '策划者'}]->(b);
MATCH (a:`Person` {`name`: '沃里克伯爵（造王者）'}) MATCH (b:`Event` {`name`: '北安普顿战役（1460）'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派将领'}]->(b);
MATCH (a:`Person` {`name`: '沃里克伯爵（造王者）'}) MATCH (b:`Event` {`name`: '埃奇科特穆尔战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '倒戈统帅'}]->(b);
MATCH (a:`Person` {`name`: '沃里克伯爵（造王者）'}) MATCH (b:`Event` {`name`: '巴尼特战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'lancaster', `role`: '阵亡'}]->(b);
MATCH (a:`Person` {`name`: '沃里克伯爵（造王者）'}) MATCH (b:`Event` {`name`: '陶顿战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派将领'}]->(b);
MATCH (a:`Person` {`name`: '爱德华一世（长腿爱德华）'}) MATCH (b:`Event` {`name`: '埃夫舍姆之战'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '胜利王子'}]->(b);
MATCH (a:`Person` {`name`: '爱德华一世（长腿爱德华）'}) MATCH (b:`Event` {`name`: '爱德华一世征服威尔士'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '征服者'}]->(b);
MATCH (a:`Person` {`name`: '爱德华三世'}) MATCH (b:`Event` {`name`: '1373年英葡同盟条约'}) CREATE (a)-[:`PARTICIPATED_IN`]->(b);
MATCH (a:`Person` {`name`: '爱德华三世'}) MATCH (b:`Event` {`name`: '百年战争爆发'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '宣战者'}]->(b);
MATCH (a:`Person` {`name`: '爱德华五世'}) MATCH (b:`Event` {`name`: '伦敦塔王子'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '失踪王子'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Event` {`name`: '埃奇科特穆尔战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '被囚'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Event` {`name`: '巴尼特战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派统帅'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Event` {`name`: '爱德华四世驾崩'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '驾崩君主'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Event` {`name`: '特克斯伯里战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派统帅'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Event` {`name`: '玫瑰战争开端（第一次圣奥尔本斯）'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '约克一方'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Event` {`name`: '莫蒂默十字战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派统帅'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Event` {`name`: '陶顿战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派统帅'}]->(b);
MATCH (a:`Person` {`name`: '理查三世'}) MATCH (b:`Event` {`name`: '伦敦塔王子'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '取代者'}]->(b);
MATCH (a:`Person` {`name`: '理查三世'}) MATCH (b:`Event` {`name`: '博斯沃思原野战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '阵亡'}]->(b);
MATCH (a:`Person` {`name`: '理查三世'}) MATCH (b:`Event` {`name`: '博斯沃思原野战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '战败者'}]->(b);
MATCH (a:`Person` {`name`: '理查二世'}) MATCH (b:`Event` {`name`: '1381年农民起义'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '当事君主'}]->(b);
MATCH (a:`Person` {`name`: '理查二世'}) MATCH (b:`Event` {`name`: '1386年温莎条约'}) CREATE (a)-[:`PARTICIPATED_IN`]->(b);
MATCH (a:`Person` {`name`: '理查二世'}) MATCH (b:`Event` {`name`: '理查二世被废黜'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '被废者'}]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Event` {`name`: '北安普顿战役（1460）'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派统帅'}]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Event` {`name`: '协调法案'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '继承人'}]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Event` {`name`: '第一次圣奥尔本斯战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '约克派统帅'}]->(b);
MATCH (a:`Person` {`name`: '理查，约克公爵'}) MATCH (b:`Event` {`name`: '韦克菲尔德战役'}) CREATE (a)-[:`PARTICIPATED_IN` {`faction`: 'york', `role`: '阵亡'}]->(b);
MATCH (a:`Person` {`name`: '约翰王'}) MATCH (b:`Event` {`name`: '《大宪章》'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '被迫签署'}]->(b);
MATCH (a:`Person` {`name`: '约翰王'}) MATCH (b:`Event` {`name`: '腓力二世收复诺曼底'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '失守一方'}]->(b);
MATCH (a:`Person` {`name`: '腓力二世（奥古斯都）'}) MATCH (b:`Event` {`name`: '腓力二世收复诺曼底'}) CREATE (a)-[:`PARTICIPATED_IN` {`role`: '征服者'}]->(b);
MATCH (a:`Person` {`name`: '若昂一世'}) MATCH (b:`Event` {`name`: '1386年温莎条约'}) CREATE (a)-[:`PARTICIPATED_IN`]->(b);
MATCH (a:`Event` {`name`: '富尔福德门之战'}) MATCH (b:`Event` {`name`: '诺曼征服'}) CREATE (a)-[:`PART_OF`]->(b);
MATCH (a:`Event` {`name`: '斯坦福桥之战'}) MATCH (b:`Event` {`name`: '诺曼征服'}) CREATE (a)-[:`PART_OF`]->(b);
MATCH (a:`Event` {`name`: '黑斯廷斯之战'}) MATCH (b:`Event` {`name`: '诺曼征服'}) CREATE (a)-[:`PART_OF`]->(b);
MATCH (a:`Event` {`name`: '10 世纪收复丹麦法区'}) MATCH (b:`Event` {`name`: '927 年英格兰统一'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '1066 英格兰继承危机'}) MATCH (b:`Event` {`name`: '黑斯廷斯之战'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '1373年英葡同盟条约'}) MATCH (b:`Event` {`name`: '1386年温莎条约'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '1381年农民起义'}) MATCH (b:`Event` {`name`: '理查二世被废黜'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '《大宪章》'}) MATCH (b:`Event` {`name`: '埃夫舍姆之战'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '丢盔原野战役'}) MATCH (b:`Event` {`name`: '亨利六世复位'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '亨利二世即位'}) MATCH (b:`Event` {`name`: '《大宪章》'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '亨利六世之死'}) MATCH (b:`Event` {`name`: '爱德华四世驾崩'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '亨利六世复位'}) MATCH (b:`Event` {`name`: '巴尼特战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '伦敦塔王子'}) MATCH (b:`Event` {`name`: '白金汉叛乱'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '北安普顿战役（1460）'}) MATCH (b:`Event` {`name`: '协调法案'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '协调法案'}) MATCH (b:`Event` {`name`: '韦克菲尔德战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '博斯沃思原野战役'}) MATCH (b:`Event` {`name`: '斯托克菲尔德战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '卢德福德桥对峙'}) MATCH (b:`Event` {`name`: '北安普顿战役（1460）'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '埃夫舍姆之战'}) MATCH (b:`Event` {`name`: '爱德华一世征服威尔士'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '埃奇科特穆尔战役'}) MATCH (b:`Event` {`name`: '丢盔原野战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '大异教军'}) MATCH (b:`Event` {`name`: '爱丁顿战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '富尔福德门之战'}) MATCH (b:`Event` {`name`: '斯坦福桥之战'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '巴尼特战役'}) MATCH (b:`Event` {`name`: '特克斯伯里战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '布洛尔希思战役'}) MATCH (b:`Event` {`name`: '卢德福德桥对峙'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '斯坦福桥之战'}) MATCH (b:`Event` {`name`: '黑斯廷斯之战'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '爱丁顿战役'}) MATCH (b:`Event` {`name`: '韦德莫尔条约'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '爱德华一世征服威尔士'}) MATCH (b:`Event` {`name`: '百年战争爆发'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '爱德华四世驾崩'}) MATCH (b:`Event` {`name`: '伦敦塔王子'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '特克斯伯里战役'}) MATCH (b:`Event` {`name`: '亨利六世之死'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '玫瑰战争开端（第一次圣奥尔本斯）'}) MATCH (b:`Event` {`name`: '第一次圣奥尔本斯战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '理查二世被废黜'}) MATCH (b:`Event` {`name`: '阿金库尔战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '白金汉叛乱'}) MATCH (b:`Event` {`name`: '博斯沃思原野战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '百年战争爆发'}) MATCH (b:`Event` {`name`: '1381年农民起义'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '第一次圣奥尔本斯战役'}) MATCH (b:`Event` {`name`: '布洛尔希思战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '第二次圣奥尔本斯战役'}) MATCH (b:`Event` {`name`: '陶顿战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '莫蒂默十字战役'}) MATCH (b:`Event` {`name`: '第二次圣奥尔本斯战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '赫克瑟姆战役'}) MATCH (b:`Event` {`name`: '埃奇科特穆尔战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '赫奇利穆尔战役'}) MATCH (b:`Event` {`name`: '赫克瑟姆战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '赫尔格河之战'}) MATCH (b:`Event` {`name`: '斯蒂克莱斯塔德战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '阿尔弗雷德—古斯伦条约'}) MATCH (b:`Event` {`name`: '10 世纪收复丹麦法区'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '阿金库尔战役'}) MATCH (b:`Event` {`name`: '玫瑰战争开端（第一次圣奥尔本斯）'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '陶顿战役'}) MATCH (b:`Event` {`name`: '赫奇利穆尔战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '韦克菲尔德战役'}) MATCH (b:`Event` {`name`: '莫蒂默十字战役'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '韦德莫尔条约'}) MATCH (b:`Event` {`name`: '阿尔弗雷德—古斯伦条约'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Event` {`name`: '黑斯廷斯之战'}) MATCH (b:`Event` {`name`: '诺曼征服'}) CREATE (a)-[:`PRECEDES`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔斯坦'}) MATCH (b:`Event` {`name`: '927 年英格兰统一'}) CREATE (a)-[:`PROCLAIMED`]->(b);
MATCH (a:`Event` {`name`: '沃灵福德条约'}) MATCH (b:`Person` {`name`: '亨利二世'}) CREATE (a)-[:`RECOGNIZED_HEIR`]->(b);
MATCH (a:`Event` {`name`: '阿尔弗雷德—古斯伦条约'}) MATCH (b:`Event` {`name`: '丹麦金'}) CREATE (a)-[:`RELATED_TO`]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Person` {`name`: '伊迪丝（威塞克斯王后）'}) CREATE (a)-[:`RELATED_TO` {`kinship`: '兄妹', `via`: '同为戈德温与戈蒂之子'}]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`RELATED_TO` {`description`: '母戈蒂为乌尔夫之妹，乌尔夫娶克努特之妹埃斯特里德，哈罗德经母系与耶灵丹麦王族为姻亲', `kinship`: '丹麦王室姻亲', `line`: '母系', `path`: '哈罗德 → 母戈蒂 → 兄乌尔夫 → 妻埃斯特里德 → 兄克努特'}]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Person` {`name`: '埃斯特里德·斯韦恩斯达特'}) CREATE (a)-[:`RELATED_TO` {`description`: '舅父乌尔夫之妻，克努特之妹，丹麦公主', `kinship`: '姨母（姻亲）', `line`: '母系'}]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Person` {`name`: '忏悔者爱德华'}) CREATE (a)-[:`RELATED_TO` {`description`: '爱德华王后伊迪丝之兄，无血缘姻亲', `kinship`: '妻兄', `via`: '妹伊迪丝'}]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Person` {`name`: '斯韦恩二世（埃斯特里德森）'}) CREATE (a)-[:`RELATED_TO` {`description`: '斯韦恩二世为乌尔夫与埃斯特里德之子，哈罗德按母系与其为堂表亲', `kinship`: '堂表亲（母系）', `line`: '母系', `path`: '哈罗德 → 母戈蒂 → 兄乌尔夫 → 子斯韦恩二世'}]->(b);
MATCH (a:`Person` {`name`: '埃斯特里德·斯韦恩斯达特'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`RELATED_TO` {`description`: '斯韦恩一世之女，克努特大帝之妹', `kinship`: '兄妹'}]->(b);
MATCH (a:`Person` {`name`: '戈蒂·托克尔之女'}) MATCH (b:`Person` {`name`: '乌尔夫·托吉尔森'}) CREATE (a)-[:`RELATED_TO` {`description`: '同为托尔吉尔·斯普拉凯灵之子，戈蒂嫁英格兰戈德温，乌尔夫娶丹麦公主埃斯特里德', `kinship`: '兄妹'}]->(b);
MATCH (a:`Dynasty` {`name`: '卡佩王朝'}) MATCH (b:`Kingdom` {`name`: '法兰西王国'}) CREATE (a)-[:`RULED`]->(b);
MATCH (a:`Dynasty` {`name`: '诺曼王朝'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED`]->(b);
MATCH (a:`Person` {`name`: '丹麦哈拉尔二世'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 1018, `start_year`: 1014, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '亨利一世'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1135, `note`: '1106年征服诺曼底后重新统一', `start_year`: 1106, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '亨利三世'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1259, `note`: '1259年《巴黎条约》放弃声索；此后英王仅对海峡群岛保留相关名义', `start_year`: 1216, `title`: '诺曼底公爵（名义）'}]->(b);
MATCH (a:`Person` {`name`: '亨利三世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1272, `start_year`: 1216, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '亨利二世'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1189, `note`: '1150年受封，金雀花王朝起点', `start_year`: 1150, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '亨利二世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1189, `start_year`: 1154, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '亨利五世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1422, `start_year`: 1413, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1471, `note`: '1461-1470、1471间歇被约克取代', `start_year`: 1422, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '亨利四世（博林布鲁克）'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1413, `start_year`: 1399, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 1035, `start_year`: 1018, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Kingdom` {`name`: '挪威'}) CREATE (a)-[:`RULED` {`end_year`: 1035, `start_year`: 1028, `title`: '挪威国王'}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Kingdom` {`name`: '瑞典南部'}) CREATE (a)-[:`RULED` {`end_year`: 1035, `start_year`: 1026, `title`: '瑞典南部统治者'}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1035, `start_year`: 1016, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 1014, `start_year`: 986, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1014, `note`: '短暂征服，1014年2月卒', `start_year`: 1013, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·兔足'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1040, `start_year`: 1035, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·蓝牙'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 986, `start_year`: 958, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '哈瑟克努特'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 1042, `start_year`: 1035, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '哈瑟克努特'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1042, `start_year`: 1040, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '埃塞尔斯坦'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 939, `start_year`: 924, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德一世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 871, `start_year`: 865, `title`: '威塞克斯国王'}]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1016, `note`: '1013-1014短暂被克努特取代', `start_year`: 978, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '埃尔夫威德'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 924, `start_year`: 924, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '埃德加（和平者）'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 975, `start_year`: 959, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '埃德威格'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 959, `start_year`: 955, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '埃德蒙一世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 946, `start_year`: 939, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '埃德雷德'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 955, `start_year`: 946, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '奥拉夫二世（圣奥拉夫）'}) MATCH (b:`Kingdom` {`name`: '挪威'}) CREATE (a)-[:`RULED` {`end_year`: 1028, `note`: '1028年被克努特驱逐', `start_year`: 1015, `title`: '挪威国王'}]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1087, `start_year`: 1035, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1087, `start_year`: 1066, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '威廉一世·长剑'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 942, `start_year`: 927, `title`: '鲁昂伯爵'}]->(b);
MATCH (a:`Person` {`name`: '忏悔者爱德华'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1066, `start_year`: 1042, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '斐迪南一世'}) MATCH (b:`Kingdom` {`name`: '葡萄牙王国'}) CREATE (a)-[:`RULED`]->(b);
MATCH (a:`Person` {`name`: '斯蒂芬'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1144, `start_year`: 1135, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '斯韦恩二世（埃斯特里德森）'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 1074, `start_year`: 1047, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '殉教者爱德华'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 978, `start_year`: 975, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '爱德华一世（长腿爱德华）'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1307, `start_year`: 1272, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '爱德华三世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1377, `start_year`: 1327, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '爱德华二世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1327, `start_year`: 1307, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '爱德华五世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1483, `start_year`: 1483, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1483, `note`: '1470-1471亨利六世复位期间流亡', `start_year`: 1461, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '爱德华长者'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 924, `start_year`: 899, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '理查一世（无畏者）'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 996, `start_year`: 942, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '理查一世（狮心王）'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1199, `start_year`: 1189, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '理查一世（狮心王）'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1199, `start_year`: 1189, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '理查三世'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1027, `start_year`: 1026, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '理查三世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1485, `start_year`: 1483, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '理查二世'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1399, `start_year`: 1377, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '理查二世（善良者）'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1027, `note`: '约1006年起正式称公爵', `start_year`: 996, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '约翰王'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1204, `note`: '1204年失大陆诺曼底', `start_year`: 1199, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '约翰王'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1216, `start_year`: 1199, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '罗伯特·柯索斯'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1106, `start_year`: 1087, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '罗伯特一世（宽宏者）'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1035, `start_year`: 1027, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '罗洛'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 927, `start_year`: 911, `title`: '诺曼人之首（无固定公爵号）'}]->(b);
MATCH (a:`Person` {`name`: '老戈姆'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 958, `start_year`: 936, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '胡安一世'}) MATCH (b:`Kingdom` {`name`: '卡斯蒂利亚王国'}) CREATE (a)-[:`RULED`]->(b);
MATCH (a:`Person` {`name`: '若弗鲁瓦五世（美男子）'}) MATCH (b:`Fief` {`name`: '诺曼底公国'}) CREATE (a)-[:`RULED` {`end_year`: 1150, `note`: '安茹伯爵征服诺曼底', `start_year`: 1144, `title`: '诺曼底公爵'}]->(b);
MATCH (a:`Person` {`name`: '若昂一世'}) MATCH (b:`Kingdom` {`name`: '葡萄牙王国'}) CREATE (a)-[:`RULED`]->(b);
MATCH (a:`Person` {`name`: '铁甲埃德蒙'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 1016, `start_year`: 1016, `title`: '英格兰国王'}]->(b);
MATCH (a:`Person` {`name`: '阿尔弗雷德大帝'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED` {`end_year`: 899, `start_year`: 871, `title`: '威塞克斯国王'}]->(b);
MATCH (a:`Person` {`name`: '马格努斯一世（好人）'}) MATCH (b:`Kingdom` {`name`: '丹麦'}) CREATE (a)-[:`RULED` {`end_year`: 1047, `start_year`: 1042, `title`: '丹麦国王'}]->(b);
MATCH (a:`Person` {`name`: '马格努斯一世（好人）'}) MATCH (b:`Kingdom` {`name`: '挪威'}) CREATE (a)-[:`RULED` {`end_year`: 1047, `start_year`: 1035, `title`: '挪威国王'}]->(b);
MATCH (a:`Dynasty` {`name`: '勃艮第王朝'}) MATCH (b:`Kingdom` {`name`: '葡萄牙王国'}) CREATE (a)-[:`RULED_OVER`]->(b);
MATCH (a:`Dynasty` {`name`: '诺曼王朝'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED_OVER` {`period`: '1066-1154'}]->(b);
MATCH (a:`Dynasty` {`name`: '金雀花王朝'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`RULED_OVER` {`period`: '1154-1485'}]->(b);
MATCH (a:`Dynasty` {`name`: '阿维斯王朝'}) MATCH (b:`Kingdom` {`name`: '葡萄牙王国'}) CREATE (a)-[:`RULED_OVER`]->(b);
MATCH (a:`Event` {`name`: '玫瑰战争开端（第一次圣奥尔本斯）'}) MATCH (b:`Event` {`name`: '第一次圣奥尔本斯战役'}) CREATE (a)-[:`SAME_AS`]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Person` {`name`: '安茹的玛格丽特'}) CREATE (a)-[:`SPOUSE_OF`]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '诺曼底的埃玛'}) CREATE (a)-[:`SPOUSE_OF`]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) MATCH (b:`Person` {`name`: '诺曼底的埃玛'}) CREATE (a)-[:`SPOUSE_OF`]->(b);
MATCH (a:`Person` {`name`: '丹麦哈拉尔二世'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1018年克努特击败兄哈拉尔二世，统一丹麦', `inherited_title`: ['丹麦国王'], `succession_type`: '兄弟征服', `year`: 1018}]->(b);
MATCH (a:`Person` {`name`: '于格·卡佩'}) MATCH (b:`Person` {`name`: '罗贝尔二世（虔诚者）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '于格·卡佩之子罗贝尔二世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '亨利一世'}) MATCH (b:`Person` {`name`: '斯蒂芬'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1135年斯蒂芬同时取得英格兰王位与诺曼底公爵领', `inheritance_descriptions`: ['亨利一世曾指定女儿玛蒂尔达继承；其侄斯蒂芬（威廉一世之外孙女系）抢先加冕，引发安茹内战', '亨利一世无男嗣，外甥斯蒂芬继位；引发与玛蒂尔达之内战'], `inherited_title`: ['英格兰国王', '诺曼底公爵'], `name`: '斯蒂芬即位', `succession_types`: ['旁支继位', '侄辈继位'], `year`: 1135}]->(b);
MATCH (a:`Person` {`name`: '亨利一世'}) MATCH (b:`Person` {`name`: '斯蒂芬'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '亨利一世曾指定女儿玛蒂尔达继承；其侄斯蒂芬抢先加冕，引发安茹内战', `inherited_title`: '英格兰国王', `name`: '斯蒂芬即位', `succession_type`: '旁支继位', `year`: 1135}]->(b);
MATCH (a:`Person` {`name`: '亨利一世'}) MATCH (b:`Person` {`name`: '菲利普一世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '亨利一世之子菲利普一世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '亨利三世'}) MATCH (b:`Person` {`name`: '爱德华一世（长腿爱德华）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '亨利三世长子爱德华一世', `inherited_title`: '英格兰国王', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '亨利二世'}) MATCH (b:`Person` {`name`: '理查一世（狮心王）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1189年理查一世同时继承英格兰王位与诺曼底公爵', `inheritance_descriptions`: ['亨利二世卒，理查一世继英格兰王位', '亨利二世卒，理查一世继诺曼底公爵'], `inherited_title`: ['英格兰国王', '诺曼底公爵'], `succession_type`: '父子继承', `year`: 1189}]->(b);
MATCH (a:`Person` {`name`: '亨利五世'}) MATCH (b:`Person` {`name`: '亨利六世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '亨利五世之子亨利六世，幼主即位', `inherited_title`: '英格兰国王', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '亨利六世'}) MATCH (b:`Person` {`name`: '爱德华四世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '玫瑰战争中约克党爱德华四世取代亨利六世（非父死子继）', `inherited_title`: '英格兰国王', `succession_type`: '约克党夺位', `year`: 1461}]->(b);
MATCH (a:`Person` {`name`: '亨利四世（博林布鲁克）'}) MATCH (b:`Person` {`name`: '亨利五世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '亨利四世之子亨利五世', `inherited_title`: '英格兰国王', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '哈拉尔·兔足'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1035年克努特卒，其子哈拉尔·兔足继英格兰王位', `inherited_title`: ['英格兰国王'], `succession_type`: '父子继承', `year`: 1035}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '哈瑟克努特'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1035年克努特卒，其嫡子哈瑟克努特继丹麦王位', `inherited_title`: ['丹麦国王'], `succession_type`: '父子继承', `year`: 1035}]->(b);
MATCH (a:`Person` {`name`: '克努特大帝'}) MATCH (b:`Person` {`name`: '马格努斯一世（好人）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1035年克努特卒；挪威由奥拉夫之子马格努斯统治', `inherited_title`: ['挪威国王'], `succession_type`: '奥拉夫系继承', `year`: 1035}]->(b);
MATCH (a:`Person` {`name`: '八字胡斯韦恩'}) MATCH (b:`Person` {`name`: '丹麦哈拉尔二世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1014年斯韦恩在英格兰卒；其兄哈拉尔二世暂据丹麦', `inherited_title`: ['丹麦国王'], `succession_type`: '父子继承', `year`: 1014}]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·兔足'}) MATCH (b:`Person` {`name`: '哈瑟克努特'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1040年哈拉尔·兔足卒，其异母弟哈瑟克努特继英格兰王位', `inherited_title`: ['英格兰国王'], `succession_type`: '兄弟继承', `year`: 1040}]->(b);
MATCH (a:`Person` {`name`: '哈拉尔·蓝牙'}) MATCH (b:`Person` {`name`: '八字胡斯韦恩'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '986年蓝牙哈拉尔卒或被推翻，斯韦恩继位', `inherited_title`: ['丹麦国王'], `succession_type`: '父子继承', `year`: 986}]->(b);
MATCH (a:`Person` {`name`: '哈瑟克努特'}) MATCH (b:`Person` {`name`: '忏悔者爱德华'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1042年哈瑟克努特无嗣而卒，埃塞尔雷德二世之子忏悔者爱德华复位', `dynasty_from`: 'Jelling Dynasty / House of Knýtlinga', `dynasty_to`: 'House of Wessex', `inherited_title`: ['英格兰国王'], `succession_type`: '威塞克斯复辟', `year`: 1042}]->(b);
MATCH (a:`Person` {`name`: '哈瑟克努特'}) MATCH (b:`Person` {`name`: '马格努斯一世（好人）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1042年哈瑟克努特无嗣而卒；挪威/丹麦贵族拥立奥拉夫之子马格努斯', `dynasty_from`: 'Jelling Dynasty / House of Knýtlinga', `dynasty_to`: 'House of St. Olaf', `inherited_title`: ['丹麦国王'], `succession_type`: '选举/继承', `year`: 1042}]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Person` {`name`: '威廉一世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1066年10月黑斯廷斯之战哈罗德阵亡；12月威廉加冕为英格兰国王，诺曼征服完成', `dynasty_from`: 'House of Wessex', `dynasty_to`: 'Norman Dynasty', `inherited_title`: ['英格兰国王'], `succession_type`: '军事征服', `year`: 1066}]->(b);
MATCH (a:`Person` {`name`: '埃塞尔斯坦'}) MATCH (b:`Person` {`name`: '埃德蒙一世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '939年埃塞尔斯坦无嗣，其弟埃德蒙一世继位', `inherited_title`: ['英格兰国王'], `succession_type`: '兄弟继承', `year`: 939}]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德一世'}) MATCH (b:`Person` {`name`: '阿尔弗雷德大帝'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '871年埃塞尔雷德一世战死后，其弟阿尔弗雷德继位', `inherited_title`: ['威塞克斯国王'], `succession_type`: '兄弟继承', `year`: 871}]->(b);
MATCH (a:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) MATCH (b:`Person` {`name`: '铁甲埃德蒙'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1016年埃塞尔雷德二世卒，其子铁甲埃德蒙继位', `inherited_title`: ['英格兰国王'], `succession_type`: '父子继承', `year`: 1016}]->(b);
MATCH (a:`Person` {`name`: '埃尔夫威德'}) MATCH (b:`Person` {`name`: '埃塞尔斯坦'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '924年8月埃尔夫威德卒，其弟埃塞尔斯坦继位', `inherited_title`: ['英格兰国王'], `succession_type`: '兄弟继承', `year`: 924}]->(b);
MATCH (a:`Person` {`name`: '埃德加（和平者）'}) MATCH (b:`Person` {`name`: '殉教者爱德华'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '975年埃德加卒，长子殉教者爱德华继位', `inherited_title`: ['英格兰国王'], `succession_type`: '父子继承', `year`: 975}]->(b);
MATCH (a:`Person` {`name`: '埃德威格'}) MATCH (b:`Person` {`name`: '埃德加（和平者）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '959年埃德威格卒，其弟埃德加（和平者）继位', `inherited_title`: ['英格兰国王'], `succession_type`: '兄弟继承', `year`: 959}]->(b);
MATCH (a:`Person` {`name`: '埃德蒙一世'}) MATCH (b:`Person` {`name`: '埃德雷德'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '946年埃德蒙一世遇害，其弟埃德雷德继位', `inherited_title`: ['英格兰国王'], `succession_type`: '兄弟继承', `year`: 946}]->(b);
MATCH (a:`Person` {`name`: '埃德雷德'}) MATCH (b:`Person` {`name`: '埃德威格'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '955年埃德雷德无嗣，埃德蒙一世之子埃德威格继位', `inherited_title`: ['英格兰国王'], `succession_type`: '侄辈/旁系', `year`: 955}]->(b);
MATCH (a:`Person` {`name`: '奥拉夫二世（圣奥拉夫）'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1028年奥拉夫被克努特驱逐；1030年斯蒂克莱斯塔德战死', `inherited_title`: ['挪威国王'], `succession_type`: '军事征服', `year`: 1028}]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Person` {`name`: '威廉二世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1087年威廉一世卒，次子红毛威廉继英格兰王位（诺曼家族世系为威廉三世）', `inherited_title`: '英格兰国王', `name`: '威廉一世去世', `note`: '原事件节点 Death of William the Conqueror 信息已迁入此关系', `succession_type`: '分割继承', `year`: 1087}]->(b);
MATCH (a:`Person` {`name`: '威廉一世'}) MATCH (b:`Person` {`name`: '罗伯特·柯索斯'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1087年诺曼底世系威廉二世（征服者）卒，长子罗伯特·柯索斯继诺曼底公爵', `inherited_title`: '诺曼底公爵', `succession_type`: '分割继承', `year`: 1087}]->(b);
MATCH (a:`Person` {`name`: '威廉一世·长剑'}) MATCH (b:`Person` {`name`: '理查一世（无畏者）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '长剑威廉遇害，其子理查一世继位，诺曼政权巩固', `inherited_title`: '诺曼底公爵', `succession_type`: '父子继承', `year`: 942}]->(b);
MATCH (a:`Person` {`name`: '威廉二世'}) MATCH (b:`Person` {`name`: '亨利一世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '新森林狩猎事故，亨利一世随即即位', `inherited_title`: '英格兰国王', `name`: '红毛威廉之死', `note`: '原事件节点 Death of William Rufus 信息已迁入此关系', `succession_type`: '兄弟继承', `year`: 1100}]->(b);
MATCH (a:`Person` {`name`: '忏悔者爱德华'}) MATCH (b:`Person` {`name`: '哈罗德·戈德温森'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1066年1月忏悔者爱德华无嗣而卒；哈罗德·戈德温森（王后伊迪丝之兄）获贤人会议拥立；其家族另经母戈蒂与丹麦乌尔夫—埃斯特里德联姻，与耶灵王室有母系姻亲', `inherited_title`: ['英格兰国王'], `succession_type`: '贵族推选', `year`: 1066}]->(b);
MATCH (a:`Person` {`name`: '斯蒂芬'}) MATCH (b:`Person` {`name`: '亨利二世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1153年《温彻斯特条约》约定斯蒂芬身后由玛蒂尔达之子亨利二世继位；1154年斯蒂芬去世，安茹/金雀花统治开端', `inherited_title`: '英格兰国王', `name`: '斯蒂芬—亨利二世继承安排', `succession_type`: '条约继承', `year`: 1154}]->(b);
MATCH (a:`Person` {`name`: '斯蒂芬'}) MATCH (b:`Person` {`name`: '若弗鲁瓦五世（美男子）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1144年若弗鲁瓦五世攻占诺曼底；安茹系取代斯蒂芬对公国的控制', `inherited_title`: '诺曼底公爵', `succession_type`: '军事征服', `year`: 1144}]->(b);
MATCH (a:`Person` {`name`: '查理四世（美男子）'}) MATCH (b:`Person` {`name`: '腓力六世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '查理四世无嗣，卡佩直系终结；瓦卢瓦的查理一系侄孙腓力六世（卡佩旁支）加冕', `succession_type`: '旁支继位'}]->(b);
MATCH (a:`Person` {`name`: '殉教者爱德华'}) MATCH (b:`Person` {`name`: '埃塞尔雷德二世（无准备者）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '978年殉教者爱德华被杀，其弟埃塞尔雷德二世（无准备者）继位', `inherited_title`: ['英格兰国王'], `succession_type`: '兄弟继承', `year`: 978}]->(b);
MATCH (a:`Person` {`name`: '爱德华一世（长腿爱德华）'}) MATCH (b:`Person` {`name`: '爱德华二世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '爱德华一世之子爱德华二世', `inherited_title`: '英格兰国王', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '爱德华三世'}) MATCH (b:`Person` {`name`: '理查二世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '爱德华三世孙辈理查二世（黑太子爱德华之子）', `inherited_title`: '英格兰国王', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '爱德华二世'}) MATCH (b:`Person` {`name`: '爱德华三世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1327年爱德华二世被废，其子爱德华三世即位', `inherited_title`: '英格兰国王', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '爱德华五世'}) MATCH (b:`Person` {`name`: '理查三世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '理查三世取代爱德华五世，伦敦塔王子事件', `inherited_title`: '英格兰国王', `succession_type`: '叔侄/篡位'}]->(b);
MATCH (a:`Person` {`name`: '爱德华四世'}) MATCH (b:`Person` {`name`: '爱德华五世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '爱德华四世之子爱德华五世，在位仅数月', `inherited_title`: '英格兰国王', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '爱德华长者'}) MATCH (b:`Person` {`name`: '埃尔夫威德'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '924年7月爱德华长者卒，长子埃尔夫威德继位', `inherited_title`: ['威塞克斯国王'], `succession_type`: '父子继承', `year`: 924}]->(b);
MATCH (a:`Person` {`name`: '理查一世（无畏者）'}) MATCH (b:`Person` {`name`: '理查二世（善良者）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '理查二世为首位广泛采用「公爵」称号的诺曼统治者', `inherited_title`: '诺曼底公爵', `succession_type`: '父子继承', `year`: 996}]->(b);
MATCH (a:`Person` {`name`: '理查一世（狮心王）'}) MATCH (b:`Person` {`name`: '约翰王'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1199年约翰同时继承英格兰王位与诺曼底公爵', `inheritance_descriptions`: ['理查一世无嗣，幼弟约翰继英格兰王位', '理查一世无嗣，幼弟约翰继诺曼底公爵'], `inherited_title`: ['英格兰国王', '诺曼底公爵'], `succession_type`: '兄弟继承', `year`: 1199}]->(b);
MATCH (a:`Person` {`name`: '理查三世'}) MATCH (b:`Person` {`name`: '亨利七世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '博斯沃思战败，都铎王朝开端', `inherited_title`: '英格兰国王', `succession_type`: '战争夺位', `year`: 1485}]->(b);
MATCH (a:`Person` {`name`: '理查三世'}) MATCH (b:`Person` {`name`: '罗伯特一世（宽宏者）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '理查三世无嗣，弟罗伯特一世继位', `inherited_title`: '诺曼底公爵', `succession_type`: '兄弟继承', `year`: 1027}]->(b);
MATCH (a:`Person` {`name`: '理查二世'}) MATCH (b:`Person` {`name`: '亨利四世（博林布鲁克）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '理查二世被废，冈特的约翰之子亨利四世建立兰开斯特支系统治', `inherited_title`: '英格兰国王', `succession_type`: '篡位/旁支', `year`: 1399}]->(b);
MATCH (a:`Person` {`name`: '理查二世（善良者）'}) MATCH (b:`Person` {`name`: '理查三世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '理查二世长子理查三世继位', `inherited_title`: '诺曼底公爵', `succession_type`: '父子继承', `year`: 1026}]->(b);
MATCH (a:`Person` {`name`: '约翰王'}) MATCH (b:`Person` {`name`: '亨利三世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1216年亨利三世继英格兰王位，并保有诺曼底公爵名义声索', `inheritance_descriptions`: ['1216年约翰卒，其子亨利三世继英格兰王位', '1204年大陆诺曼底已失；1216年约翰卒后亨利三世仍自称公爵直至1259年放弃声索'], `inherited_title`: ['英格兰国王', '诺曼底公爵（名义）'], `succession_type`: '父子继承', `year`: 1216}]->(b);
MATCH (a:`Person` {`name`: '罗伯特·柯索斯'}) MATCH (b:`Person` {`name`: '亨利一世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1106年亨利一世征服诺曼底，公国与英格兰王权再度统一', `inherited_title`: '诺曼底公爵', `succession_type`: '兄弟征服', `year`: 1106}]->(b);
MATCH (a:`Person` {`name`: '罗伯特一世（宽宏者）'}) MATCH (b:`Person` {`name`: '威廉一世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '罗伯特一世卒，私生子威廉继诺曼底公爵位', `inherited_title`: '诺曼底公爵', `succession_type`: '私生子继承', `year`: 1035}]->(b);
MATCH (a:`Person` {`name`: '罗洛'}) MATCH (b:`Person` {`name`: '威廉一世·长剑'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '罗洛卒后长子长剑威廉继为诺曼人之首', `inherited_title`: '鲁昂伯爵', `succession_type`: '父子继承', `year`: 927}]->(b);
MATCH (a:`Person` {`name`: '罗贝尔二世（虔诚者）'}) MATCH (b:`Person` {`name`: '亨利一世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '罗贝尔二世之子亨利一世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '老戈姆'}) MATCH (b:`Person` {`name`: '哈拉尔·蓝牙'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '958年老戈姆卒，其子蓝牙哈拉尔继位', `inherited_title`: ['丹麦国王'], `succession_type`: '父子继承', `year`: 958}]->(b);
MATCH (a:`Person` {`name`: '腓力三世（硬汉子）'}) MATCH (b:`Person` {`name`: '腓力四世（美男子）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '腓力三世之子腓力四世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '腓力二世（奥古斯都）'}) MATCH (b:`Person` {`name`: '路易八世（狮子）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '腓力二世之子路易八世（狮子）正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '腓力五世（长人）'}) MATCH (b:`Person` {`name`: '查理四世（美男子）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '腓力五世无嗣去世，其弟查理四世继位', `succession_type`: '兄弟继承'}]->(b);
MATCH (a:`Person` {`name`: '腓力四世（美男子）'}) MATCH (b:`Person` {`name`: '路易十世（争吵者）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '腓力四世之子路易十世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '若弗鲁瓦五世（美男子）'}) MATCH (b:`Person` {`name`: '亨利二世'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1149–1150年若弗鲁瓦与玛蒂尔达将诺曼底让予亨利；1150年路易七世承认，金雀花统治开端', `inherited_title`: '诺曼底公爵', `succession_type`: '让渡/父子', `year`: 1150}]->(b);
MATCH (a:`Person` {`name`: '菲利普一世'}) MATCH (b:`Person` {`name`: '路易六世（胖子）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '菲利普一世之子路易六世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '路易七世（幼王）'}) MATCH (b:`Person` {`name`: '腓力二世（奥古斯都）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '路易七世之子腓力二世（奥古斯都）正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '路易九世（圣路易）'}) MATCH (b:`Person` {`name`: '腓力三世（硬汉子）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '路易九世之子腓力三世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '路易八世（狮子）'}) MATCH (b:`Person` {`name`: '路易九世（圣路易）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '路易八世之子路易九世（圣路易）正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '路易六世（胖子）'}) MATCH (b:`Person` {`name`: '路易七世（幼王）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '路易六世之子路易七世正常继位', `succession_type`: '父子继承'}]->(b);
MATCH (a:`Person` {`name`: '路易十世（争吵者）'}) MATCH (b:`Person` {`name`: '腓力五世（长人）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '路易十世无嗣去世，其弟腓力五世（长人）继位；涉及萨利克法与继承争议', `succession_type`: '兄弟继承'}]->(b);
MATCH (a:`Person` {`name`: '铁甲埃德蒙'}) MATCH (b:`Person` {`name`: '克努特大帝'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1016年埃德蒙与克努特议和并瓜分英格兰；埃德蒙同年卒，克努特成为全英格兰国王', `dynasty_from`: 'House of Wessex', `dynasty_to`: 'Jelling Dynasty / House of Knýtlinga', `inherited_title`: ['英格兰国王'], `succession_type`: '丹麦征服', `year`: 1016}]->(b);
MATCH (a:`Person` {`name`: '阿尔弗雷德大帝'}) MATCH (b:`Person` {`name`: '爱德华长者'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '899年阿尔弗雷德卒，长子爱德华长者继位', `inherited_title`: ['威塞克斯国王', '盎格鲁-撒克逊人之王'], `succession_type`: '父子继承', `year`: 899}]->(b);
MATCH (a:`Person` {`name`: '马格努斯一世（好人）'}) MATCH (b:`Person` {`name`: '斯韦恩二世（埃斯特里德森）'}) CREATE (a)-[:`SUCCEEDED_BY` {`description`: '1047年马格努斯战死；克努特外甥斯韦恩二世夺回丹麦，耶灵支系延续', `dynasty_from`: 'House of St. Olaf', `dynasty_to`: 'Jelling Dynasty / House of Knýtlinga', `inherited_title`: ['丹麦国王'], `succession_type`: '军事争夺', `year`: 1047}]->(b);
MATCH (a:`Person` {`name`: '玛蒂尔达皇后'}) MATCH (b:`Person` {`name`: '格洛斯特的罗伯特'}) CREATE (a)-[:`SUPPORTED_BY`]->(b);
MATCH (a:`Event` {`name`: '第一次圣奥尔本斯战役'}) MATCH (b:`Concept` {`name`: '兰开斯特红玫瑰'}) CREATE (a)-[:`SYMBOLIZED_BY`]->(b);
MATCH (a:`Event` {`name`: '第一次圣奥尔本斯战役'}) MATCH (b:`Concept` {`name`: '约克白玫瑰'}) CREATE (a)-[:`SYMBOLIZED_BY`]->(b);
MATCH (a:`Dynasty` {`name`: '勃艮第王朝'}) MATCH (b:`Dynasty` {`name`: '阿维斯王朝'}) CREATE (a)-[:`THRONE_CONTINUED_BY`]->(b);
MATCH (a:`Dynasty` {`name`: '卡佩王朝'}) MATCH (b:`Dynasty` {`name`: '瓦卢瓦王朝'}) CREATE (a)-[:`THRONE_CONTINUED_BY` {`description`: '查理四世无嗣，腓力六世（瓦卢瓦支系）加冕；卡佩直系终结、瓦卢瓦王朝开端，百年战争导火索之一', `name`: '瓦卢瓦继位', `year`: 1328}]->(b);
MATCH (a:`Dynasty` {`name`: '威塞克斯王朝'}) MATCH (b:`Dynasty` {`name`: '耶灵王朝'}) CREATE (a)-[:`THRONE_CONTINUED_BY` {`description`: '1016年克努特取代威塞克斯本土线，耶灵王朝统治英格兰', `name`: '丹麦征服', `year`: 1016}]->(b);
MATCH (a:`Dynasty` {`name`: '威塞克斯王朝'}) MATCH (b:`Dynasty` {`name`: '诺曼王朝'}) CREATE (a)-[:`THRONE_CONTINUED_BY` {`description`: '1066年黑斯廷斯后威廉一世加冕；威塞克斯本土线让位于诺曼王朝', `name`: '诺曼征服', `year`: 1066}]->(b);
MATCH (a:`Dynasty` {`name`: '耶灵王朝'}) MATCH (b:`Dynasty` {`name`: '威塞克斯王朝'}) CREATE (a)-[:`THRONE_CONTINUED_BY` {`description`: '1042年忏悔者爱德华即位，威塞克斯血脉重返英格兰王位', `name`: '威塞克斯复辟', `year`: 1042}]->(b);
MATCH (a:`Event` {`name`: '诺曼征服'}) MATCH (b:`Event` {`name`: '1066 英格兰继承危机'}) CREATE (a)-[:`TRIGGERED_BY`]->(b);
MATCH (a:`Event` {`name`: '927 年英格兰统一'}) MATCH (b:`Kingdom` {`name`: '英格兰王国'}) CREATE (a)-[:`UNIFIED`]->(b);
MATCH (a:`Person` {`name`: '亨利一世'}) MATCH (b:`Person` {`name`: '玛蒂尔达皇后'}) CREATE (a)-[:`WEAKENED_CLAIM_OF` {`description`: '亨利合法男性继承人威廉·阿德林溺亡，引发继承危机', `name`: '白船号沉没', `name_en`: 'White Ship disaster', `year`: 1120}]->(b);
MATCH (a:`Person` {`name`: '哈罗德·戈德温森'}) MATCH (b:`Event` {`name`: '斯坦福桥之战'}) CREATE (a)-[:`WON_AT`]->(b);
MATCH (a:`Person` {`name`: '阿尔弗雷德大帝'}) MATCH (b:`Event` {`name`: '爱丁顿战役'}) CREATE (a)-[:`WON_AT`]->(b);
